package it.infolabs.hibernate;

// Generated 6-mag-2010 0.12.00 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Acconto generated by hbm2java
 */
public class Acconto implements java.io.Serializable {

	private long id;
	private Fattura fattura;
	private Date data;
	private Double totale;
	private String note;

	public Acconto() {
	}

	public Acconto(long id) {
		this.id = id;
	}

	public Acconto(long id, Fattura fattura, Date data, Double totale,
			String note) {
		this.id = id;
		this.fattura = fattura;
		this.data = data;
		this.totale = totale;
		this.note = note;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Fattura getFattura() {
		return this.fattura;
	}

	public void setFattura(Fattura fattura) {
		this.fattura = fattura;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public Double getTotale() {
		return this.totale;
	}

	public void setTotale(Double totale) {
		this.totale = totale;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
