package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

/**
 * ArticoliScaricatiViewId generated by hbm2java
 */
public class ArticoliScaricatiViewId implements java.io.Serializable {

	private Long idordine;
	private Long idarticolo;
	private String codbarre;
	private String descrizione;
	private Double prezzoAcquisto;
	private Double prezzoIngrosso;
	private Double prezzoDettaglio;
	private Long iva;
	private String um;
	private Double qta;
	private Long sconto;

	public ArticoliScaricatiViewId() {
	}

	public ArticoliScaricatiViewId(Long idordine, Long idarticolo,
			String codbarre, String descrizione, Double prezzoAcquisto,
			Double prezzoIngrosso, Double prezzoDettaglio, Long iva, String um,
			Double qta, Long sconto) {
		this.idordine = idordine;
		this.idarticolo = idarticolo;
		this.codbarre = codbarre;
		this.descrizione = descrizione;
		this.prezzoAcquisto = prezzoAcquisto;
		this.prezzoIngrosso = prezzoIngrosso;
		this.prezzoDettaglio = prezzoDettaglio;
		this.iva = iva;
		this.um = um;
		this.qta = qta;
		this.sconto = sconto;
	}

	public Long getIdordine() {
		return this.idordine;
	}

	public void setIdordine(Long idordine) {
		this.idordine = idordine;
	}

	public Long getIdarticolo() {
		return this.idarticolo;
	}

	public void setIdarticolo(Long idarticolo) {
		this.idarticolo = idarticolo;
	}

	public String getCodbarre() {
		return this.codbarre;
	}

	public void setCodbarre(String codbarre) {
		this.codbarre = codbarre;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Double getPrezzoAcquisto() {
		return this.prezzoAcquisto;
	}

	public void setPrezzoAcquisto(Double prezzoAcquisto) {
		this.prezzoAcquisto = prezzoAcquisto;
	}

	public Double getPrezzoIngrosso() {
		return this.prezzoIngrosso;
	}

	public void setPrezzoIngrosso(Double prezzoIngrosso) {
		this.prezzoIngrosso = prezzoIngrosso;
	}

	public Double getPrezzoDettaglio() {
		return this.prezzoDettaglio;
	}

	public void setPrezzoDettaglio(Double prezzoDettaglio) {
		this.prezzoDettaglio = prezzoDettaglio;
	}

	public Long getIva() {
		return this.iva;
	}

	public void setIva(Long iva) {
		this.iva = iva;
	}

	public String getUm() {
		return this.um;
	}

	public void setUm(String um) {
		this.um = um;
	}

	public Double getQta() {
		return this.qta;
	}

	public void setQta(Double qta) {
		this.qta = qta;
	}

	public Long getSconto() {
		return this.sconto;
	}

	public void setSconto(Long sconto) {
		this.sconto = sconto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticoliScaricatiViewId))
			return false;
		ArticoliScaricatiViewId castOther = (ArticoliScaricatiViewId) other;

		return ((this.getIdordine() == castOther.getIdordine()) || (this
				.getIdordine() != null
				&& castOther.getIdordine() != null && this.getIdordine()
				.equals(castOther.getIdordine())))
				&& ((this.getIdarticolo() == castOther.getIdarticolo()) || (this
						.getIdarticolo() != null
						&& castOther.getIdarticolo() != null && this
						.getIdarticolo().equals(castOther.getIdarticolo())))
				&& ((this.getCodbarre() == castOther.getCodbarre()) || (this
						.getCodbarre() != null
						&& castOther.getCodbarre() != null && this
						.getCodbarre().equals(castOther.getCodbarre())))
				&& ((this.getDescrizione() == castOther.getDescrizione()) || (this
						.getDescrizione() != null
						&& castOther.getDescrizione() != null && this
						.getDescrizione().equals(castOther.getDescrizione())))
				&& ((this.getPrezzoAcquisto() == castOther.getPrezzoAcquisto()) || (this
						.getPrezzoAcquisto() != null
						&& castOther.getPrezzoAcquisto() != null && this
						.getPrezzoAcquisto().equals(
								castOther.getPrezzoAcquisto())))
				&& ((this.getPrezzoIngrosso() == castOther.getPrezzoIngrosso()) || (this
						.getPrezzoIngrosso() != null
						&& castOther.getPrezzoIngrosso() != null && this
						.getPrezzoIngrosso().equals(
								castOther.getPrezzoIngrosso())))
				&& ((this.getPrezzoDettaglio() == castOther
						.getPrezzoDettaglio()) || (this.getPrezzoDettaglio() != null
						&& castOther.getPrezzoDettaglio() != null && this
						.getPrezzoDettaglio().equals(
								castOther.getPrezzoDettaglio())))
				&& ((this.getIva() == castOther.getIva()) || (this.getIva() != null
						&& castOther.getIva() != null && this.getIva().equals(
						castOther.getIva())))
				&& ((this.getUm() == castOther.getUm()) || (this.getUm() != null
						&& castOther.getUm() != null && this.getUm().equals(
						castOther.getUm())))
				&& ((this.getQta() == castOther.getQta()) || (this.getQta() != null
						&& castOther.getQta() != null && this.getQta().equals(
						castOther.getQta())))
				&& ((this.getSconto() == castOther.getSconto()) || (this
						.getSconto() != null
						&& castOther.getSconto() != null && this.getSconto()
						.equals(castOther.getSconto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdordine() == null ? 0 : this.getIdordine().hashCode());
		result = 37
				* result
				+ (getIdarticolo() == null ? 0 : this.getIdarticolo()
						.hashCode());
		result = 37 * result
				+ (getCodbarre() == null ? 0 : this.getCodbarre().hashCode());
		result = 37
				* result
				+ (getDescrizione() == null ? 0 : this.getDescrizione()
						.hashCode());
		result = 37
				* result
				+ (getPrezzoAcquisto() == null ? 0 : this.getPrezzoAcquisto()
						.hashCode());
		result = 37
				* result
				+ (getPrezzoIngrosso() == null ? 0 : this.getPrezzoIngrosso()
						.hashCode());
		result = 37
				* result
				+ (getPrezzoDettaglio() == null ? 0 : this.getPrezzoDettaglio()
						.hashCode());
		result = 37 * result
				+ (getIva() == null ? 0 : this.getIva().hashCode());
		result = 37 * result + (getUm() == null ? 0 : this.getUm().hashCode());
		result = 37 * result
				+ (getQta() == null ? 0 : this.getQta().hashCode());
		result = 37 * result
				+ (getSconto() == null ? 0 : this.getSconto().hashCode());
		return result;
	}

}
