package it.infolabs.hibernate;

// Generated 1-feb-2010 0.56.14 by Hibernate Tools 3.2.4.GA

/**
 * ArticoliScaricatiView generated by hbm2java
 */
public class ArticoliScaricatiView implements java.io.Serializable {

	private ArticoliScaricatiViewId id;

	public ArticoliScaricatiView() {
	}

	public ArticoliScaricatiView(ArticoliScaricatiViewId id) {
		this.id = id;
	}

	public ArticoliScaricatiViewId getId() {
		return this.id;
	}

	public void setId(ArticoliScaricatiViewId id) {
		this.id = id;
	}

}
