package it.infolabs.hibernate;

// Generated 21-lug-2009 1.39.59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Aspetto generated by hbm2java
 */
public class Aspetto implements java.io.Serializable {

	private long idaspetto;
	private String nome;
	private Set<Ordini> ordinis = new HashSet<Ordini>(0);
	private Set<Ordini> ordinis_1 = new HashSet<Ordini>(0);
	private Set<Ordini> ordinis_2 = new HashSet<Ordini>(0);

	public Aspetto() {
	}

	public Aspetto(long idaspetto, String nome) {
		this.idaspetto = idaspetto;
		this.nome = nome;
	}

	public Aspetto(long idaspetto, String nome, Set<Ordini> ordinis,
			Set<Ordini> ordinis_1, Set<Ordini> ordinis_2) {
		this.idaspetto = idaspetto;
		this.nome = nome;
		this.ordinis = ordinis;
		this.ordinis_1 = ordinis_1;
		this.ordinis_2 = ordinis_2;
	}

	public long getIdaspetto() {
		return this.idaspetto;
	}

	public void setIdaspetto(long idaspetto) {
		this.idaspetto = idaspetto;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Ordini> getOrdinis() {
		return this.ordinis;
	}

	public void setOrdinis(Set<Ordini> ordinis) {
		this.ordinis = ordinis;
	}

	public Set<Ordini> getOrdinis_1() {
		return this.ordinis_1;
	}

	public void setOrdinis_1(Set<Ordini> ordinis_1) {
		this.ordinis_1 = ordinis_1;
	}

	public Set<Ordini> getOrdinis_2() {
		return this.ordinis_2;
	}

	public void setOrdinis_2(Set<Ordini> ordinis_2) {
		this.ordinis_2 = ordinis_2;
	}

}
