package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Aspetto generated by hbm2java
 */
public class Aspetto implements java.io.Serializable {

	private long idaspetto;
	private String nome;
	private Set<Scarico> ordinis = new HashSet<Scarico>(0);
	private Set<Scarico> ordinis_1 = new HashSet<Scarico>(0);
	private Set<Scarico> ordinis_2 = new HashSet<Scarico>(0);

	public Aspetto() {
	}

	public Aspetto(long idaspetto, String nome) {
		this.idaspetto = idaspetto;
		this.nome = nome;
	}

	public Aspetto(long idaspetto, String nome, Set<Scarico> ordinis,
			Set<Scarico> ordinis_1, Set<Scarico> ordinis_2) {
		this.idaspetto = idaspetto;
		this.nome = nome;
		this.ordinis = ordinis;
		this.ordinis_1 = ordinis_1;
		this.ordinis_2 = ordinis_2;
	}

	public long getIdaspetto() {
		return this.idaspetto;
	}

	public void setIdaspetto(long idaspetto) {
		this.idaspetto = idaspetto;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Scarico> getOrdinis() {
		return this.ordinis;
	}

	public void setOrdinis(Set<Scarico> ordinis) {
		this.ordinis = ordinis;
	}

	public Set<Scarico> getOrdinis_1() {
		return this.ordinis_1;
	}

	public void setOrdinis_1(Set<Scarico> ordinis_1) {
		this.ordinis_1 = ordinis_1;
	}

	public Set<Scarico> getOrdinis_2() {
		return this.ordinis_2;
	}

	public void setOrdinis_2(Set<Scarico> ordinis_2) {
		this.ordinis_2 = ordinis_2;
	}

}
