package it.infolabs.hibernate;

// Generated 6-mag-2010 0.12.00 by Hibernate Tools 3.2.4.GA

/**
 * Bolla generated by hbm2java
 */
public class Bolla implements java.io.Serializable {

	private long id;
	private Documento documento;

	public Bolla() {
	}

	public Bolla(Documento documento) {
		this.documento = documento;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

}
