package it.infolabs.hibernate;

// Generated 22-nov-2009 2.09.36 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaCliente generated by hbm2java
 */
public class CategoriaCliente implements java.io.Serializable {

	private long id;
	private String descrizione;
	private Set<Clienti> clientis = new HashSet<Clienti>(0);

	public CategoriaCliente() {
	}

	public CategoriaCliente(long id) {
		this.id = id;
	}

	public CategoriaCliente(long id, String descrizione, Set<Clienti> clientis) {
		this.id = id;
		this.descrizione = descrizione;
		this.clientis = clientis;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Clienti> getClientis() {
		return this.clientis;
	}

	public void setClientis(Set<Clienti> clientis) {
		this.clientis = clientis;
	}

}
