package it.infolabs.hibernate;

// Generated 27-giu-2010 12.59.16 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Causale generated by hbm2java
 */
public class Causale implements java.io.Serializable {

	private long idcausale;
	private String nome;
	private Set<Scarico> scaricos = new HashSet<Scarico>(0);
	private Set<Ddt> ddts = new HashSet<Ddt>(0);

	public Causale() {
	}

	public Causale(long idcausale, String nome) {
		this.idcausale = idcausale;
		this.nome = nome;
	}

	public Causale(long idcausale, String nome, Set<Scarico> scaricos,
			Set<Ddt> ddts) {
		this.idcausale = idcausale;
		this.nome = nome;
		this.scaricos = scaricos;
		this.ddts = ddts;
	}

	public long getIdcausale() {
		return this.idcausale;
	}

	public void setIdcausale(long idcausale) {
		this.idcausale = idcausale;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Scarico> getScaricos() {
		return this.scaricos;
	}

	public void setScaricos(Set<Scarico> scaricos) {
		this.scaricos = scaricos;
	}

	public Set<Ddt> getDdts() {
		return this.ddts;
	}

	public void setDdts(Set<Ddt> ddts) {
		this.ddts = ddts;
	}

}
