package it.infolabs.hibernate;

// Generated 21-nov-2009 23.21.44 by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
 * Clienti generated by hbm2java
 */
public class Clienti implements java.io.Serializable {

	private long idcliente;
	private DocumentoCliente documentoCliente;
	private Provincia provincia;
	private Ente ente;
	private Date dataInserimento;
	private String nome;
	private String cognome;
	private String piva;
	private String codfisc;
	private String via;
	private String cap;
	private String citta;
	private String tel;
	private String cell;
	private String fax;
	private String email;
	private String website;
	private String note;
	private Date dataNascita;
	private String numDoc;
	private Date rilasciatoIl;
	private String natoA;
	private String intestazione;
	private Long nazionalita;
	private String rilasciatoDi;
	private String tel2;
	private String cell2;
	private Long categoriaCliente;

	public Clienti() {
	}

	public Clienti(long idcliente, String nome, String cognome) {
		this.idcliente = idcliente;
		this.nome = nome;
		this.cognome = cognome;
	}

	public Clienti(long idcliente, DocumentoCliente documentoCliente,
			Provincia provincia, Ente ente, Date dataInserimento, String nome,
			String cognome, String piva, String codfisc, String via,
			String cap, String citta, String tel, String cell, String fax,
			String email, String website, String note, Date dataNascita,
			String numDoc, Date rilasciatoIl, String natoA,
			String intestazione, Long nazionalita, String rilasciatoDi,
			String tel2, String cell2, Long categoriaCliente) {
		this.idcliente = idcliente;
		this.documentoCliente = documentoCliente;
		this.provincia = provincia;
		this.ente = ente;
		this.dataInserimento = dataInserimento;
		this.nome = nome;
		this.cognome = cognome;
		this.piva = piva;
		this.codfisc = codfisc;
		this.via = via;
		this.cap = cap;
		this.citta = citta;
		this.tel = tel;
		this.cell = cell;
		this.fax = fax;
		this.email = email;
		this.website = website;
		this.note = note;
		this.dataNascita = dataNascita;
		this.numDoc = numDoc;
		this.rilasciatoIl = rilasciatoIl;
		this.natoA = natoA;
		this.intestazione = intestazione;
		this.nazionalita = nazionalita;
		this.rilasciatoDi = rilasciatoDi;
		this.tel2 = tel2;
		this.cell2 = cell2;
		this.categoriaCliente = categoriaCliente;
	}

	public long getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(long idcliente) {
		this.idcliente = idcliente;
	}

	public DocumentoCliente getDocumentoCliente() {
		return this.documentoCliente;
	}

	public void setDocumentoCliente(DocumentoCliente documentoCliente) {
		this.documentoCliente = documentoCliente;
	}

	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	public Ente getEnte() {
		return this.ente;
	}

	public void setEnte(Ente ente) {
		this.ente = ente;
	}

	public Date getDataInserimento() {
		return this.dataInserimento;
	}

	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCognome() {
		return this.cognome;
	}

	public void setCognome(String cognome) {
		this.cognome = cognome;
	}

	public String getPiva() {
		return this.piva;
	}

	public void setPiva(String piva) {
		this.piva = piva;
	}

	public String getCodfisc() {
		return this.codfisc;
	}

	public void setCodfisc(String codfisc) {
		this.codfisc = codfisc;
	}

	public String getVia() {
		return this.via;
	}

	public void setVia(String via) {
		this.via = via;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getCitta() {
		return this.citta;
	}

	public void setCitta(String citta) {
		this.citta = citta;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getCell() {
		return this.cell;
	}

	public void setCell(String cell) {
		this.cell = cell;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getDataNascita() {
		return this.dataNascita;
	}

	public void setDataNascita(Date dataNascita) {
		this.dataNascita = dataNascita;
	}

	public String getNumDoc() {
		return this.numDoc;
	}

	public void setNumDoc(String numDoc) {
		this.numDoc = numDoc;
	}

	public Date getRilasciatoIl() {
		return this.rilasciatoIl;
	}

	public void setRilasciatoIl(Date rilasciatoIl) {
		this.rilasciatoIl = rilasciatoIl;
	}

	public String getNatoA() {
		return this.natoA;
	}

	public void setNatoA(String natoA) {
		this.natoA = natoA;
	}

	public String getIntestazione() {
		return this.intestazione;
	}

	public void setIntestazione(String intestazione) {
		this.intestazione = intestazione;
	}

	public Long getNazionalita() {
		return this.nazionalita;
	}

	public void setNazionalita(Long nazionalita) {
		this.nazionalita = nazionalita;
	}

	public String getRilasciatoDi() {
		return this.rilasciatoDi;
	}

	public void setRilasciatoDi(String rilasciatoDi) {
		this.rilasciatoDi = rilasciatoDi;
	}

	public String getTel2() {
		return this.tel2;
	}

	public void setTel2(String tel2) {
		this.tel2 = tel2;
	}

	public String getCell2() {
		return this.cell2;
	}

	public void setCell2(String cell2) {
		this.cell2 = cell2;
	}

	public Long getCategoriaCliente() {
		return this.categoriaCliente;
	}

	public void setCategoriaCliente(Long categoriaCliente) {
		this.categoriaCliente = categoriaCliente;
	}

}
