package it.infolabs.hibernate;

// Generated 27-giu-2010 12.41.21 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * CodiciIva generated by hbm2java
 */
public class CodiciIva implements java.io.Serializable {

	private long id;
	private String codice;
	private long percentuale;
	private String descrizione;
	private String descrizioneBreve;
	private Set<DettaglioDocumento> dettaglioDocumentos = new HashSet<DettaglioDocumento>(
			0);
	private Set<Carico> caricos = new HashSet<Carico>(0);
	private Set<DettaglioScarico> dettaglioScaricos = new HashSet<DettaglioScarico>(
			0);
	private Set<Scarico> scaricos = new HashSet<Scarico>(0);
	private Set<Articolo> articolos = new HashSet<Articolo>(0);
	private Set<DettaglioScaricoManuale> dettaglioScaricoManuales = new HashSet<DettaglioScaricoManuale>(
			0);

	public CodiciIva() {
	}

	public CodiciIva(long id, String codice, long percentuale) {
		this.id = id;
		this.codice = codice;
		this.percentuale = percentuale;
	}

	public CodiciIva(long id, String codice, long percentuale,
			String descrizione, String descrizioneBreve,
			Set<DettaglioDocumento> dettaglioDocumentos, Set<Carico> caricos,
			Set<DettaglioScarico> dettaglioScaricos, Set<Scarico> scaricos,
			Set<Articolo> articolos,
			Set<DettaglioScaricoManuale> dettaglioScaricoManuales) {
		this.id = id;
		this.codice = codice;
		this.percentuale = percentuale;
		this.descrizione = descrizione;
		this.descrizioneBreve = descrizioneBreve;
		this.dettaglioDocumentos = dettaglioDocumentos;
		this.caricos = caricos;
		this.dettaglioScaricos = dettaglioScaricos;
		this.scaricos = scaricos;
		this.articolos = articolos;
		this.dettaglioScaricoManuales = dettaglioScaricoManuales;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	public long getPercentuale() {
		return this.percentuale;
	}

	public void setPercentuale(long percentuale) {
		this.percentuale = percentuale;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getDescrizioneBreve() {
		return this.descrizioneBreve;
	}

	public void setDescrizioneBreve(String descrizioneBreve) {
		this.descrizioneBreve = descrizioneBreve;
	}

	public Set<DettaglioDocumento> getDettaglioDocumentos() {
		return this.dettaglioDocumentos;
	}

	public void setDettaglioDocumentos(
			Set<DettaglioDocumento> dettaglioDocumentos) {
		this.dettaglioDocumentos = dettaglioDocumentos;
	}

	public Set<Carico> getCaricos() {
		return this.caricos;
	}

	public void setCaricos(Set<Carico> caricos) {
		this.caricos = caricos;
	}

	public Set<DettaglioScarico> getDettaglioScaricos() {
		return this.dettaglioScaricos;
	}

	public void setDettaglioScaricos(Set<DettaglioScarico> dettaglioScaricos) {
		this.dettaglioScaricos = dettaglioScaricos;
	}

	public Set<Scarico> getScaricos() {
		return this.scaricos;
	}

	public void setScaricos(Set<Scarico> scaricos) {
		this.scaricos = scaricos;
	}

	public Set<Articolo> getArticolos() {
		return this.articolos;
	}

	public void setArticolos(Set<Articolo> articolos) {
		this.articolos = articolos;
	}

	public Set<DettaglioScaricoManuale> getDettaglioScaricoManuales() {
		return this.dettaglioScaricoManuales;
	}

	public void setDettaglioScaricoManuales(
			Set<DettaglioScaricoManuale> dettaglioScaricoManuales) {
		this.dettaglioScaricoManuales = dettaglioScaricoManuales;
	}

}
