package it.infolabs.hibernate;

// Generated 6-mag-2010 0.12.00 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Consegna generated by hbm2java
 */
public class Consegna implements java.io.Serializable {

	private long id;
	private String descrizione;
	private Set<Ddt> ddts = new HashSet<Ddt>(0);
	private Set<Ddt> ddts_1 = new HashSet<Ddt>(0);

	public Consegna() {
	}

	public Consegna(long id) {
		this.id = id;
	}

	public Consegna(long id, String descrizione, Set<Ddt> ddts, Set<Ddt> ddts_1) {
		this.id = id;
		this.descrizione = descrizione;
		this.ddts = ddts;
		this.ddts_1 = ddts_1;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Ddt> getDdts() {
		return this.ddts;
	}

	public void setDdts(Set<Ddt> ddts) {
		this.ddts = ddts;
	}

	public Set<Ddt> getDdts_1() {
		return this.ddts_1;
	}

	public void setDdts_1(Set<Ddt> ddts_1) {
		this.ddts_1 = ddts_1;
	}

}
