package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * ContoBancario generated by hbm2java
 */
public class ContoBancario implements java.io.Serializable {

	private long idconto;
	private Banca banca;
	private Integer abi;
	private Integer cab;
	private Integer cc;
	private String iban;
	private Set<MovimentoBanca> movimentoBancas = new HashSet<MovimentoBanca>(0);
	private Set<MovimentoBanca> movimentoBancas_1 = new HashSet<MovimentoBanca>(
			0);
	private Set<MovimentoBanca> movimentoBancas_2 = new HashSet<MovimentoBanca>(
			0);

	public ContoBancario() {
	}

	public ContoBancario(long idconto, Banca banca) {
		this.idconto = idconto;
		this.banca = banca;
	}

	public ContoBancario(long idconto, Banca banca, Integer abi, Integer cab,
			Integer cc, String iban, Set<MovimentoBanca> movimentoBancas,
			Set<MovimentoBanca> movimentoBancas_1,
			Set<MovimentoBanca> movimentoBancas_2) {
		this.idconto = idconto;
		this.banca = banca;
		this.abi = abi;
		this.cab = cab;
		this.cc = cc;
		this.iban = iban;
		this.movimentoBancas = movimentoBancas;
		this.movimentoBancas_1 = movimentoBancas_1;
		this.movimentoBancas_2 = movimentoBancas_2;
	}

	public long getIdconto() {
		return this.idconto;
	}

	public void setIdconto(long idconto) {
		this.idconto = idconto;
	}

	public Banca getBanca() {
		return this.banca;
	}

	public void setBanca(Banca banca) {
		this.banca = banca;
	}

	public Integer getAbi() {
		return this.abi;
	}

	public void setAbi(Integer abi) {
		this.abi = abi;
	}

	public Integer getCab() {
		return this.cab;
	}

	public void setCab(Integer cab) {
		this.cab = cab;
	}

	public Integer getCc() {
		return this.cc;
	}

	public void setCc(Integer cc) {
		this.cc = cc;
	}

	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	public Set<MovimentoBanca> getMovimentoBancas() {
		return this.movimentoBancas;
	}

	public void setMovimentoBancas(Set<MovimentoBanca> movimentoBancas) {
		this.movimentoBancas = movimentoBancas;
	}

	public Set<MovimentoBanca> getMovimentoBancas_1() {
		return this.movimentoBancas_1;
	}

	public void setMovimentoBancas_1(Set<MovimentoBanca> movimentoBancas_1) {
		this.movimentoBancas_1 = movimentoBancas_1;
	}

	public Set<MovimentoBanca> getMovimentoBancas_2() {
		return this.movimentoBancas_2;
	}

	public void setMovimentoBancas_2(Set<MovimentoBanca> movimentoBancas_2) {
		this.movimentoBancas_2 = movimentoBancas_2;
	}

}
