package it.infolabs.hibernate;

// Generated 27-giu-2010 12.59.16 by Hibernate Tools 3.2.4.GA

/**
 * Ddt generated by hbm2java
 */
public class Ddt implements java.io.Serializable {

	private long id;
	private Porto porto;
	private Causale causale;
	private Pagamento pagamento;
	private Consegna consegna;
	private Destinazione destinazione;
	private String serie;
	private Double sconto;
	private Double speseTrasporto;
	private Double speseIncasso;
	private String riferimento;
	private Integer colli;

	public Ddt() {
	}

	public Ddt(long id) {
		this.id = id;
	}

	public Ddt(long id, Porto porto, Causale causale, Pagamento pagamento,
			Consegna consegna, Destinazione destinazione, String serie,
			Double sconto, Double speseTrasporto, Double speseIncasso,
			String riferimento, Integer colli) {
		this.id = id;
		this.porto = porto;
		this.causale = causale;
		this.pagamento = pagamento;
		this.consegna = consegna;
		this.destinazione = destinazione;
		this.serie = serie;
		this.sconto = sconto;
		this.speseTrasporto = speseTrasporto;
		this.speseIncasso = speseIncasso;
		this.riferimento = riferimento;
		this.colli = colli;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Porto getPorto() {
		return this.porto;
	}

	public void setPorto(Porto porto) {
		this.porto = porto;
	}

	public Causale getCausale() {
		return this.causale;
	}

	public void setCausale(Causale causale) {
		this.causale = causale;
	}

	public Pagamento getPagamento() {
		return this.pagamento;
	}

	public void setPagamento(Pagamento pagamento) {
		this.pagamento = pagamento;
	}

	public Consegna getConsegna() {
		return this.consegna;
	}

	public void setConsegna(Consegna consegna) {
		this.consegna = consegna;
	}

	public Destinazione getDestinazione() {
		return this.destinazione;
	}

	public void setDestinazione(Destinazione destinazione) {
		this.destinazione = destinazione;
	}

	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	public Double getSconto() {
		return this.sconto;
	}

	public void setSconto(Double sconto) {
		this.sconto = sconto;
	}

	public Double getSpeseTrasporto() {
		return this.speseTrasporto;
	}

	public void setSpeseTrasporto(Double speseTrasporto) {
		this.speseTrasporto = speseTrasporto;
	}

	public Double getSpeseIncasso() {
		return this.speseIncasso;
	}

	public void setSpeseIncasso(Double speseIncasso) {
		this.speseIncasso = speseIncasso;
	}

	public String getRiferimento() {
		return this.riferimento;
	}

	public void setRiferimento(String riferimento) {
		this.riferimento = riferimento;
	}

	public Integer getColli() {
		return this.colli;
	}

	public void setColli(Integer colli) {
		this.colli = colli;
	}

}
