package it.infolabs.hibernate;

// Generated 27-giu-2010 12.59.16 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Destinazione generated by hbm2java
 */
public class Destinazione implements java.io.Serializable {

	private long id;
	private Paese paese;
	private String ragioneSociale;
	private Character piva;
	private Character coficeFiscale;
	private String indirizzo;
	private String cap;
	private Character localita;
	private String provincia;
	private Character telefono;
	private Character fax;
	private Character email;
	private Character cellulare;
	private String note;
	private Set<Ddt> ddts = new HashSet<Ddt>(0);

	public Destinazione() {
	}

	public Destinazione(long id) {
		this.id = id;
	}

	public Destinazione(long id, Paese paese, String ragioneSociale,
			Character piva, Character coficeFiscale, String indirizzo,
			String cap, Character localita, String provincia,
			Character telefono, Character fax, Character email,
			Character cellulare, String note, Set<Ddt> ddts) {
		this.id = id;
		this.paese = paese;
		this.ragioneSociale = ragioneSociale;
		this.piva = piva;
		this.coficeFiscale = coficeFiscale;
		this.indirizzo = indirizzo;
		this.cap = cap;
		this.localita = localita;
		this.provincia = provincia;
		this.telefono = telefono;
		this.fax = fax;
		this.email = email;
		this.cellulare = cellulare;
		this.note = note;
		this.ddts = ddts;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Paese getPaese() {
		return this.paese;
	}

	public void setPaese(Paese paese) {
		this.paese = paese;
	}

	public String getRagioneSociale() {
		return this.ragioneSociale;
	}

	public void setRagioneSociale(String ragioneSociale) {
		this.ragioneSociale = ragioneSociale;
	}

	public Character getPiva() {
		return this.piva;
	}

	public void setPiva(Character piva) {
		this.piva = piva;
	}

	public Character getCoficeFiscale() {
		return this.coficeFiscale;
	}

	public void setCoficeFiscale(Character coficeFiscale) {
		this.coficeFiscale = coficeFiscale;
	}

	public String getIndirizzo() {
		return this.indirizzo;
	}

	public void setIndirizzo(String indirizzo) {
		this.indirizzo = indirizzo;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public Character getLocalita() {
		return this.localita;
	}

	public void setLocalita(Character localita) {
		this.localita = localita;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public Character getTelefono() {
		return this.telefono;
	}

	public void setTelefono(Character telefono) {
		this.telefono = telefono;
	}

	public Character getFax() {
		return this.fax;
	}

	public void setFax(Character fax) {
		this.fax = fax;
	}

	public Character getEmail() {
		return this.email;
	}

	public void setEmail(Character email) {
		this.email = email;
	}

	public Character getCellulare() {
		return this.cellulare;
	}

	public void setCellulare(Character cellulare) {
		this.cellulare = cellulare;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set<Ddt> getDdts() {
		return this.ddts;
	}

	public void setDdts(Set<Ddt> ddts) {
		this.ddts = ddts;
	}

}
