package it.infolabs.hibernate;

// Generated 21-lug-2009 1.39.59 by Hibernate Tools 3.2.4.GA

/**
 * DettaglioOrdineManualeId generated by hbm2java
 */
public class DettaglioOrdineManualeId implements java.io.Serializable {

	private long id;
	private long ordine;

	public DettaglioOrdineManualeId() {
	}

	public DettaglioOrdineManualeId(long id, long ordine) {
		this.id = id;
		this.ordine = ordine;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public long getOrdine() {
		return this.ordine;
	}

	public void setOrdine(long ordine) {
		this.ordine = ordine;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DettaglioOrdineManualeId))
			return false;
		DettaglioOrdineManualeId castOther = (DettaglioOrdineManualeId) other;

		return (this.getId() == castOther.getId())
				&& (this.getOrdine() == castOther.getOrdine());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result + (int) this.getOrdine();
		return result;
	}

}
