package it.infolabs.hibernate;

// Generated 16-mag-2010 11.17.51 by Hibernate Tools 3.2.4.GA

/**
 * DettaglioScaricoManuale generated by hbm2java
 */
public class DettaglioScaricoManuale implements java.io.Serializable {

	private DettaglioScaricoManualeId id;
	private CodiciIva codiciIva;
	private Scarico scarico;
	private String descrizione;
	private double qta;
	private Long sconto;
	private Double prezzoVendita;

	public DettaglioScaricoManuale() {
	}

	public DettaglioScaricoManuale(DettaglioScaricoManualeId id,
			Scarico scarico, String descrizione, double qta) {
		this.id = id;
		this.scarico = scarico;
		this.descrizione = descrizione;
		this.qta = qta;
	}

	public DettaglioScaricoManuale(DettaglioScaricoManualeId id,
			CodiciIva codiciIva, Scarico scarico, String descrizione,
			double qta, Long sconto, Double prezzoVendita) {
		this.id = id;
		this.codiciIva = codiciIva;
		this.scarico = scarico;
		this.descrizione = descrizione;
		this.qta = qta;
		this.sconto = sconto;
		this.prezzoVendita = prezzoVendita;
	}

	public DettaglioScaricoManualeId getId() {
		return this.id;
	}

	public void setId(DettaglioScaricoManualeId id) {
		this.id = id;
	}

	public CodiciIva getCodiciIva() {
		return this.codiciIva;
	}

	public void setCodiciIva(CodiciIva codiciIva) {
		this.codiciIva = codiciIva;
	}

	public Scarico getScarico() {
		return this.scarico;
	}

	public void setScarico(Scarico scarico) {
		this.scarico = scarico;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public double getQta() {
		return this.qta;
	}

	public void setQta(double qta) {
		this.qta = qta;
	}

	public Long getSconto() {
		return this.sconto;
	}

	public void setSconto(Long sconto) {
		this.sconto = sconto;
	}

	public Double getPrezzoVendita() {
		return this.prezzoVendita;
	}

	public void setPrezzoVendita(Double prezzoVendita) {
		this.prezzoVendita = prezzoVendita;
	}

}
