package it.infolabs.hibernate;

// Generated 1-feb-2010 0.56.14 by Hibernate Tools 3.2.4.GA

/**
 * DettaglioScarico generated by hbm2java
 */
public class DettaglioScarico implements java.io.Serializable {

	private DettaglioScaricoId id;
	private Scarico scarico;
	private Articolo articolo;
	private double qta;
	private Long sconto;
	private Double prezzoAcquisto;
	private Double prezzoVendita;
	private Integer iva;

	public DettaglioScarico() {
	}

	public DettaglioScarico(DettaglioScaricoId id, Scarico scarico,
			Articolo articolo, double qta) {
		this.id = id;
		this.scarico = scarico;
		this.articolo = articolo;
		this.qta = qta;
	}

	public DettaglioScarico(DettaglioScaricoId id, Scarico scarico,
			Articolo articolo, double qta, Long sconto, Double prezzoAcquisto,
			Double prezzoVendita, Integer iva) {
		this.id = id;
		this.scarico = scarico;
		this.articolo = articolo;
		this.qta = qta;
		this.sconto = sconto;
		this.prezzoAcquisto = prezzoAcquisto;
		this.prezzoVendita = prezzoVendita;
		this.iva = iva;
	}

	public DettaglioScaricoId getId() {
		return this.id;
	}

	public void setId(DettaglioScaricoId id) {
		this.id = id;
	}

	public Scarico getScarico() {
		return this.scarico;
	}

	public void setScarico(Scarico scarico) {
		this.scarico = scarico;
	}

	public Articolo getArticolo() {
		return this.articolo;
	}

	public void setArticolo(Articolo articolo) {
		this.articolo = articolo;
	}

	public double getQta() {
		return this.qta;
	}

	public void setQta(double qta) {
		this.qta = qta;
	}

	public Long getSconto() {
		return this.sconto;
	}

	public void setSconto(Long sconto) {
		this.sconto = sconto;
	}

	public Double getPrezzoAcquisto() {
		return this.prezzoAcquisto;
	}

	public void setPrezzoAcquisto(Double prezzoAcquisto) {
		this.prezzoAcquisto = prezzoAcquisto;
	}

	public Double getPrezzoVendita() {
		return this.prezzoVendita;
	}

	public void setPrezzoVendita(Double prezzoVendita) {
		this.prezzoVendita = prezzoVendita;
	}

	public Integer getIva() {
		return this.iva;
	}

	public void setIva(Integer iva) {
		this.iva = iva;
	}

}
