package it.infolabs.hibernate;

// Generated 21-lug-2009 1.39.59 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fornitori generated by hbm2java
 */
public class Fornitori implements java.io.Serializable {

	private long idfornitore;
	private Provincia provincia;
	private Date dataInserimento;
	private String nome;
	private String piva;
	private String codfisc;
	private String via;
	private String cap;
	private String citta;
	private String tel;
	private String cell;
	private String fax;
	private String email;
	private String website;
	private String note;
	private String codbarre;
	private Set<Carichi> carichis = new HashSet<Carichi>(0);
	private Set<Carichi> carichis_1 = new HashSet<Carichi>(0);
	private Set<Carichi> carichis_2 = new HashSet<Carichi>(0);
	private Set<Articoli> articolis = new HashSet<Articoli>(0);
	private Set<Articoli> articolis_1 = new HashSet<Articoli>(0);
	private Set<Articoli> articolis_2 = new HashSet<Articoli>(0);

	public Fornitori() {
	}

	public Fornitori(long idfornitore, String nome) {
		this.idfornitore = idfornitore;
		this.nome = nome;
	}

	public Fornitori(long idfornitore, Provincia provincia,
			Date dataInserimento, String nome, String piva, String codfisc,
			String via, String cap, String citta, String tel, String cell,
			String fax, String email, String website, String note,
			String codbarre, Set<Carichi> carichis, Set<Carichi> carichis_1,
			Set<Carichi> carichis_2, Set<Articoli> articolis,
			Set<Articoli> articolis_1, Set<Articoli> articolis_2) {
		this.idfornitore = idfornitore;
		this.provincia = provincia;
		this.dataInserimento = dataInserimento;
		this.nome = nome;
		this.piva = piva;
		this.codfisc = codfisc;
		this.via = via;
		this.cap = cap;
		this.citta = citta;
		this.tel = tel;
		this.cell = cell;
		this.fax = fax;
		this.email = email;
		this.website = website;
		this.note = note;
		this.codbarre = codbarre;
		this.carichis = carichis;
		this.carichis_1 = carichis_1;
		this.carichis_2 = carichis_2;
		this.articolis = articolis;
		this.articolis_1 = articolis_1;
		this.articolis_2 = articolis_2;
	}

	public long getIdfornitore() {
		return this.idfornitore;
	}

	public void setIdfornitore(long idfornitore) {
		this.idfornitore = idfornitore;
	}

	public Provincia getProvincia() {
		return this.provincia;
	}

	public void setProvincia(Provincia provincia) {
		this.provincia = provincia;
	}

	public Date getDataInserimento() {
		return this.dataInserimento;
	}

	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getPiva() {
		return this.piva;
	}

	public void setPiva(String piva) {
		this.piva = piva;
	}

	public String getCodfisc() {
		return this.codfisc;
	}

	public void setCodfisc(String codfisc) {
		this.codfisc = codfisc;
	}

	public String getVia() {
		return this.via;
	}

	public void setVia(String via) {
		this.via = via;
	}

	public String getCap() {
		return this.cap;
	}

	public void setCap(String cap) {
		this.cap = cap;
	}

	public String getCitta() {
		return this.citta;
	}

	public void setCitta(String citta) {
		this.citta = citta;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getCell() {
		return this.cell;
	}

	public void setCell(String cell) {
		this.cell = cell;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getCodbarre() {
		return this.codbarre;
	}

	public void setCodbarre(String codbarre) {
		this.codbarre = codbarre;
	}

	public Set<Carichi> getCarichis() {
		return this.carichis;
	}

	public void setCarichis(Set<Carichi> carichis) {
		this.carichis = carichis;
	}

	public Set<Carichi> getCarichis_1() {
		return this.carichis_1;
	}

	public void setCarichis_1(Set<Carichi> carichis_1) {
		this.carichis_1 = carichis_1;
	}

	public Set<Carichi> getCarichis_2() {
		return this.carichis_2;
	}

	public void setCarichis_2(Set<Carichi> carichis_2) {
		this.carichis_2 = carichis_2;
	}

	public Set<Articoli> getArticolis() {
		return this.articolis;
	}

	public void setArticolis(Set<Articoli> articolis) {
		this.articolis = articolis;
	}

	public Set<Articoli> getArticolis_1() {
		return this.articolis_1;
	}

	public void setArticolis_1(Set<Articoli> articolis_1) {
		this.articolis_1 = articolis_1;
	}

	public Set<Articoli> getArticolis_2() {
		return this.articolis_2;
	}

	public void setArticolis_2(Set<Articoli> articolis_2) {
		this.articolis_2 = articolis_2;
	}

}
