package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

/**
 * GiacenzaArticoliView generated by hbm2java
 */
public class GiacenzaArticoliView implements java.io.Serializable {

	private GiacenzaArticoliViewId id;

	public GiacenzaArticoliView() {
	}

	public GiacenzaArticoliView(GiacenzaArticoliViewId id) {
		this.id = id;
	}

	public GiacenzaArticoliViewId getId() {
		return this.id;
	}

	public void setId(GiacenzaArticoliViewId id) {
		this.id = id;
	}

}
