package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

/**
 * GiacenzaArticoliAllView generated by hbm2java
 */
public class GiacenzaArticoliAllView implements java.io.Serializable {

	private GiacenzaArticoliAllViewId id;

	public GiacenzaArticoliAllView() {
	}

	public GiacenzaArticoliAllView(GiacenzaArticoliAllViewId id) {
		this.id = id;
	}

	public GiacenzaArticoliAllViewId getId() {
		return this.id;
	}

	public void setId(GiacenzaArticoliAllViewId id) {
		this.id = id;
	}

}
