package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

/**
 * ImmagineArticolo generated by hbm2java
 */
public class ImmagineArticolo implements java.io.Serializable {

	private long id;
	private Articoli articoli;
	private String nome;
	private String estensione;
	private byte[] file;

	public ImmagineArticolo() {
	}

	public ImmagineArticolo(long id, String nome) {
		this.id = id;
		this.nome = nome;
	}

	public ImmagineArticolo(long id, Articoli articoli, String nome,
			String estensione, byte[] file) {
		this.id = id;
		this.articoli = articoli;
		this.nome = nome;
		this.estensione = estensione;
		this.file = file;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Articoli getArticoli() {
		return this.articoli;
	}

	public void setArticoli(Articoli articoli) {
		this.articoli = articoli;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEstensione() {
		return this.estensione;
	}

	public void setEstensione(String estensione) {
		this.estensione = estensione;
	}

	public byte[] getFile() {
		return this.file;
	}

	public void setFile(byte[] file) {
		this.file = file;
	}

}
