package it.infolabs.hibernate;

// Generated 6-mag-2010 0.12.00 by Hibernate Tools 3.2.4.GA

/**
 * Ordine generated by hbm2java
 */
public class Ordine implements java.io.Serializable {

	private long id;
	private Stato stato;
	private Documento documento;
	private Pagamento pagamento;
	private Integer sconto;
	private Double speseTrasporto;
	private Double speseIncasso;
	private String annotazioni;
	private String notePagamento;
	private String bancaAbi;
	private String bancaCab;
	private String bancaIban;
	private Integer convertito;
	private String tipoDocumento;

	public Ordine() {
	}

	public Ordine(Documento documento) {
		this.documento = documento;
	}

	public Ordine(Stato stato, Documento documento, Pagamento pagamento,
			Integer sconto, Double speseTrasporto, Double speseIncasso,
			String annotazioni, String notePagamento, String bancaAbi,
			String bancaCab, String bancaIban, Integer convertito,
			String tipoDocumento) {
		this.stato = stato;
		this.documento = documento;
		this.pagamento = pagamento;
		this.sconto = sconto;
		this.speseTrasporto = speseTrasporto;
		this.speseIncasso = speseIncasso;
		this.annotazioni = annotazioni;
		this.notePagamento = notePagamento;
		this.bancaAbi = bancaAbi;
		this.bancaCab = bancaCab;
		this.bancaIban = bancaIban;
		this.convertito = convertito;
		this.tipoDocumento = tipoDocumento;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Stato getStato() {
		return this.stato;
	}

	public void setStato(Stato stato) {
		this.stato = stato;
	}

	public Documento getDocumento() {
		return this.documento;
	}

	public void setDocumento(Documento documento) {
		this.documento = documento;
	}

	public Pagamento getPagamento() {
		return this.pagamento;
	}

	public void setPagamento(Pagamento pagamento) {
		this.pagamento = pagamento;
	}

	public Integer getSconto() {
		return this.sconto;
	}

	public void setSconto(Integer sconto) {
		this.sconto = sconto;
	}

	public Double getSpeseTrasporto() {
		return this.speseTrasporto;
	}

	public void setSpeseTrasporto(Double speseTrasporto) {
		this.speseTrasporto = speseTrasporto;
	}

	public Double getSpeseIncasso() {
		return this.speseIncasso;
	}

	public void setSpeseIncasso(Double speseIncasso) {
		this.speseIncasso = speseIncasso;
	}

	public String getAnnotazioni() {
		return this.annotazioni;
	}

	public void setAnnotazioni(String annotazioni) {
		this.annotazioni = annotazioni;
	}

	public String getNotePagamento() {
		return this.notePagamento;
	}

	public void setNotePagamento(String notePagamento) {
		this.notePagamento = notePagamento;
	}

	public String getBancaAbi() {
		return this.bancaAbi;
	}

	public void setBancaAbi(String bancaAbi) {
		this.bancaAbi = bancaAbi;
	}

	public String getBancaCab() {
		return this.bancaCab;
	}

	public void setBancaCab(String bancaCab) {
		this.bancaCab = bancaCab;
	}

	public String getBancaIban() {
		return this.bancaIban;
	}

	public void setBancaIban(String bancaIban) {
		this.bancaIban = bancaIban;
	}

	public Integer getConvertito() {
		return this.convertito;
	}

	public void setConvertito(Integer convertito) {
		this.convertito = convertito;
	}

	public String getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(String tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

}
