package it.infolabs.hibernate;

// Generated 26-ago-2009 22.04.11 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * Pannelli generated by hbm2java
 */
public class Pannelli implements java.io.Serializable {

	private long idpannelli;
	private String nome;
	private Set articolis = new HashSet(0);

	public Pannelli() {
	}

	public Pannelli(long idpannelli) {
		this.idpannelli = idpannelli;
	}

	public Pannelli(long idpannelli, String nome, Set articolis) {
		this.idpannelli = idpannelli;
		this.nome = nome;
		this.articolis = articolis;
	}

	public long getIdpannelli() {
		return this.idpannelli;
	}

	public void setIdpannelli(long idpannelli) {
		this.idpannelli = idpannelli;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set getArticolis() {
		return this.articolis;
	}

	public void setArticolis(Set articolis) {
		this.articolis = articolis;
	}

}
