package it.infolabs.hibernate;

// Generated 3-lug-2010 0.47.58 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	private long idprovincia;
	private String provincia;
	private String targa;
	private Set<Fornitore> fornitores = new HashSet<Fornitore>(0);
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Provincia() {
	}

	public Provincia(long idprovincia, String provincia) {
		this.idprovincia = idprovincia;
		this.provincia = provincia;
	}

	public Provincia(long idprovincia, String provincia, String targa,
			Set<Fornitore> fornitores, Set<Cliente> clientes) {
		this.idprovincia = idprovincia;
		this.provincia = provincia;
		this.targa = targa;
		this.fornitores = fornitores;
		this.clientes = clientes;
	}

	public long getIdprovincia() {
		return this.idprovincia;
	}

	public void setIdprovincia(long idprovincia) {
		this.idprovincia = idprovincia;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getTarga() {
		return this.targa;
	}

	public void setTarga(String targa) {
		this.targa = targa;
	}

	public Set<Fornitore> getFornitores() {
		return this.fornitores;
	}

	public void setFornitores(Set<Fornitore> fornitores) {
		this.fornitores = fornitores;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
