package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

/**
 * QtaCaricateView generated by hbm2java
 */
public class QtaCaricateView implements java.io.Serializable {

	private QtaCaricateViewId id;

	public QtaCaricateView() {
	}

	public QtaCaricateView(QtaCaricateViewId id) {
		this.id = id;
	}

	public QtaCaricateViewId getId() {
		return this.id;
	}

	public void setId(QtaCaricateViewId id) {
		this.id = id;
	}

}
