package it.infolabs.hibernate;

// Generated 3-lug-2010 0.47.58 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento implements java.io.Serializable {

	private long iddocumento;
	private String tipo;
	private String descrizione;
	private Set<Carico> caricos = new HashSet<Carico>(0);
	private Set<Scarico> scaricos = new HashSet<Scarico>(0);

	public TipoDocumento() {
	}

	public TipoDocumento(long iddocumento, String tipo) {
		this.iddocumento = iddocumento;
		this.tipo = tipo;
	}

	public TipoDocumento(long iddocumento, String tipo, String descrizione,
			Set<Carico> caricos, Set<Scarico> scaricos) {
		this.iddocumento = iddocumento;
		this.tipo = tipo;
		this.descrizione = descrizione;
		this.caricos = caricos;
		this.scaricos = scaricos;
	}

	public long getIddocumento() {
		return this.iddocumento;
	}

	public void setIddocumento(long iddocumento) {
		this.iddocumento = iddocumento;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Carico> getCaricos() {
		return this.caricos;
	}

	public void setCaricos(Set<Carico> caricos) {
		this.caricos = caricos;
	}

	public Set<Scarico> getScaricos() {
		return this.scaricos;
	}

	public void setScaricos(Set<Scarico> scaricos) {
		this.scaricos = scaricos;
	}

}
