package it.infolabs.hibernate;

// Generated 23-lug-2009 15.44.29 by Hibernate Tools 3.2.4.GA

/**
 * U88fax generated by hbm2java
 */
public class U88fax implements java.io.Serializable {

	private long id;
	private String kilogrammi;
	private String grammi;
	private String codiceAams;

	public U88fax() {
	}

	public U88fax(long id) {
		this.id = id;
	}

	public U88fax(long id, String kilogrammi, String grammi, String codiceAams) {
		this.id = id;
		this.kilogrammi = kilogrammi;
		this.grammi = grammi;
		this.codiceAams = codiceAams;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getKilogrammi() {
		return this.kilogrammi;
	}

	public void setKilogrammi(String kilogrammi) {
		this.kilogrammi = kilogrammi;
	}

	public String getGrammi() {
		return this.grammi;
	}

	public void setGrammi(String grammi) {
		this.grammi = grammi;
	}

	public String getCodiceAams() {
		return this.codiceAams;
	}

	public void setCodiceAams(String codiceAams) {
		this.codiceAams = codiceAams;
	}

}
