package it.infolabs.hibernate;
// Generated 3-lug-2010 0.38.48 by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Um generated by hbm2java
 */
public class Um  implements java.io.Serializable {


     private long idum;
     private String nome;
     private String descrizione;
     private Set<Articolo> articolos = new HashSet<Articolo>(0);

    public Um() {
    }

	
    public Um(long idum, String nome) {
        this.idum = idum;
        this.nome = nome;
    }
    public Um(long idum, String nome, String descrizione, Set<Articolo> articolos) {
       this.idum = idum;
       this.nome = nome;
       this.descrizione = descrizione;
       this.articolos = articolos;
    }
   
    public long getIdum() {
        return this.idum;
    }
    
    public void setIdum(long idum) {
        this.idum = idum;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
    public Set<Articolo> getArticolos() {
        return this.articolos;
    }
    
    public void setArticolos(Set<Articolo> articolos) {
        this.articolos = articolos;
    }




}


