package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

/**
 * TmpScelti generated by hbm2java
 */
public class TmpScelti implements java.io.Serializable {

	private TmpSceltiId id;

	public TmpScelti() {
	}

	public TmpScelti(TmpSceltiId id) {
		this.id = id;
	}

	public TmpSceltiId getId() {
		return this.id;
	}

	public void setId(TmpSceltiId id) {
		this.id = id;
	}

}
