package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * Camera generated by hbm2java
 */
public class Camera implements java.io.Serializable {

	private int id;
	private Integer numCamera;
	private String descrizione;
	private Integer NPosti;
	private String note;

	public Camera() {
	}

	public Camera(int id) {
		this.id = id;
	}

	public Camera(int id, Integer numCamera, String descrizione,
			Integer NPosti, String note) {
		this.id = id;
		this.numCamera = numCamera;
		this.descrizione = descrizione;
		this.NPosti = NPosti;
		this.note = note;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getNumCamera() {
		return this.numCamera;
	}

	public void setNumCamera(Integer numCamera) {
		this.numCamera = numCamera;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Integer getNPosti() {
		return this.NPosti;
	}

	public void setNPosti(Integer NPosti) {
		this.NPosti = NPosti;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
