package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * CamPrenotataId generated by hbm2java
 */
public class CamPrenotataId implements java.io.Serializable {

	private int idPrenotazione;
	private int idCamera;

	public CamPrenotataId() {
	}

	public CamPrenotataId(int idPrenotazione, int idCamera) {
		this.idPrenotazione = idPrenotazione;
		this.idCamera = idCamera;
	}

	public int getIdPrenotazione() {
		return this.idPrenotazione;
	}

	public void setIdPrenotazione(int idPrenotazione) {
		this.idPrenotazione = idPrenotazione;
	}

	public int getIdCamera() {
		return this.idCamera;
	}

	public void setIdCamera(int idCamera) {
		this.idCamera = idCamera;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CamPrenotataId))
			return false;
		CamPrenotataId castOther = (CamPrenotataId) other;

		return (this.getIdPrenotazione() == castOther.getIdPrenotazione())
				&& (this.getIdCamera() == castOther.getIdCamera());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPrenotazione();
		result = 37 * result + this.getIdCamera();
		return result;
	}

}
