package erreeffe.entity;
// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Listino generated by hbm2java
 */
public class Listino  implements java.io.Serializable {


     private long idlistino;
     private String descrizione;
     private String note;
     private Set<Convenzione> convenziones = new HashSet<Convenzione>(0);

    public Listino() {
    }

	
    public Listino(long idlistino, String descrizione) {
        this.idlistino = idlistino;
        this.descrizione = descrizione;
    }
    public Listino(long idlistino, String descrizione, String note, Set<Convenzione> convenziones) {
       this.idlistino = idlistino;
       this.descrizione = descrizione;
       this.note = note;
       this.convenziones = convenziones;
    }
   
    public long getIdlistino() {
        return this.idlistino;
    }
    
    public void setIdlistino(long idlistino) {
        this.idlistino = idlistino;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set<Convenzione> getConvenziones() {
        return this.convenziones;
    }
    
    public void setConvenziones(Set<Convenzione> convenziones) {
        this.convenziones = convenziones;
    }




}


