package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Sala generated by hbm2java
 */
public class Sala implements java.io.Serializable {

	private long id;
	private String descrizione;
	private Set<Tavolo> tavolos = new HashSet<Tavolo>(0);

	public Sala() {
	}

	public Sala(long id, String descrizione) {
		this.id = id;
		this.descrizione = descrizione;
	}

	public Sala(long id, String descrizione, Set<Tavolo> tavolos) {
		this.id = id;
		this.descrizione = descrizione;
		this.tavolos = tavolos;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Tavolo> getTavolos() {
		return this.tavolos;
	}

	public void setTavolos(Set<Tavolo> tavolos) {
		this.tavolos = tavolos;
	}

}
