package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * Utenti generated by hbm2java
 */
public class Utenti implements java.io.Serializable {

	private UtentiId id;

	public Utenti() {
	}

	public Utenti(UtentiId id) {
		this.id = id;
	}

	public UtentiId getId() {
		return this.id;
	}

	public void setId(UtentiId id) {
		this.id = id;
	}

}
