package erreeffe.entity;

// Generated 28-giu-2009 12.52.19 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentoCliente generated by hbm2java
 */
public class DocumentoCliente implements java.io.Serializable {

	private long id;
	private String descrizione;
	private String abbreviazione;
	private Set<Clienti> clientis = new HashSet<Clienti>(0);

	public DocumentoCliente() {
	}

	public DocumentoCliente(long id, String descrizione) {
		this.id = id;
		this.descrizione = descrizione;
	}

	public DocumentoCliente(long id, String descrizione, String abbreviazione,
			Set<Clienti> clientis) {
		this.id = id;
		this.descrizione = descrizione;
		this.abbreviazione = abbreviazione;
		this.clientis = clientis;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getAbbreviazione() {
		return this.abbreviazione;
	}

	public void setAbbreviazione(String abbreviazione) {
		this.abbreviazione = abbreviazione;
	}

	public Set<Clienti> getClientis() {
		return this.clientis;
	}

	public void setClientis(Set<Clienti> clientis) {
		this.clientis = clientis;
	}

}
