package erreeffe.entity;

// Generated 28-giu-2009 12.52.19 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Nazionalita generated by hbm2java
 */
public class Nazionalita implements java.io.Serializable {

	private long idnazionalita;
	private String descrizione;
	private Set<Clienti> clientis = new HashSet<Clienti>(0);

	public Nazionalita() {
	}

	public Nazionalita(long idnazionalita, String descrizione) {
		this.idnazionalita = idnazionalita;
		this.descrizione = descrizione;
	}

	public Nazionalita(long idnazionalita, String descrizione,
			Set<Clienti> clientis) {
		this.idnazionalita = idnazionalita;
		this.descrizione = descrizione;
		this.clientis = clientis;
	}

	public long getIdnazionalita() {
		return this.idnazionalita;
	}

	public void setIdnazionalita(long idnazionalita) {
		this.idnazionalita = idnazionalita;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Clienti> getClientis() {
		return this.clientis;
	}

	public void setClientis(Set<Clienti> clientis) {
		this.clientis = clientis;
	}

}
