package erreeffe.entity;

// Generated 28-giu-2009 12.52.19 by Hibernate Tools 3.2.4.GA

/**
 * Progressivi generated by hbm2java
 */
public class Progressivi implements java.io.Serializable {

	private int anno;
	private int progFattura;
	private int progRicevuta;
	private int progScontrino;
	private int progNonFiscale;

	public Progressivi() {
	}

	public Progressivi(int anno, int progFattura, int progRicevuta,
			int progScontrino, int progNonFiscale) {
		this.anno = anno;
		this.progFattura = progFattura;
		this.progRicevuta = progRicevuta;
		this.progScontrino = progScontrino;
		this.progNonFiscale = progNonFiscale;
	}

	public int getAnno() {
		return this.anno;
	}

	public void setAnno(int anno) {
		this.anno = anno;
	}

	public int getProgFattura() {
		return this.progFattura;
	}

	public void setProgFattura(int progFattura) {
		this.progFattura = progFattura;
	}

	public int getProgRicevuta() {
		return this.progRicevuta;
	}

	public void setProgRicevuta(int progRicevuta) {
		this.progRicevuta = progRicevuta;
	}

	public int getProgScontrino() {
		return this.progScontrino;
	}

	public void setProgScontrino(int progScontrino) {
		this.progScontrino = progScontrino;
	}

	public int getProgNonFiscale() {
		return this.progNonFiscale;
	}

	public void setProgNonFiscale(int progNonFiscale) {
		this.progNonFiscale = progNonFiscale;
	}

}
