package erreeffe.entity;

// Generated 28-giu-2009 12.52.19 by Hibernate Tools 3.2.4.GA

/**
 * Utenti generated by hbm2java
 */
public class Utenti implements java.io.Serializable {

	private UtentiId id;

	public Utenti() {
	}

	public Utenti(UtentiId id) {
		this.id = id;
	}

	public UtentiId getId() {
		return this.id;
	}

	public void setId(UtentiId id) {
		this.id = id;
	}

}
