package erreeffe.entity;

// Generated 30-giu-2009 3.07.23 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Articoli generated by hbm2java
 */
public class Articoli implements java.io.Serializable {

	private long idarticolo;
	private Fornitori fornitori;
	private Reparti reparti;
	private Um um;
	private String codfornitore;
	private String codbarre;
	private String descrizione;
	private Double prezzoAcquisto;
	private Long iva;
	private Double prezzoDettaglio;
	private Double prezzoIngrosso;
	private String imballo;
	private Long peso;
	private Long sconto;
	private String colore;
	private Long scortaMinima;
	private String note;
	private Date dataInserimento;
	private Long caricoIniziale;
	private Set<DettaglioCarichi> dettaglioCarichis = new HashSet<DettaglioCarichi>(
			0);
	private Set<ImmagineArticolo> immagineArticolos = new HashSet<ImmagineArticolo>(
			0);
	private Set<DettaglioOrdini> dettaglioOrdinis = new HashSet<DettaglioOrdini>(
			0);

	public Articoli() {
	}

	public Articoli(long idarticolo, String descrizione) {
		this.idarticolo = idarticolo;
		this.descrizione = descrizione;
	}

	public Articoli(long idarticolo, Fornitori fornitori, Reparti reparti,
			Um um, String codfornitore, String codbarre, String descrizione,
			Double prezzoAcquisto, Long iva, Double prezzoDettaglio,
			Double prezzoIngrosso, String imballo, Long peso, Long sconto,
			String colore, Long scortaMinima, String note,
			Date dataInserimento, Long caricoIniziale,
			Set<DettaglioCarichi> dettaglioCarichis,
			Set<ImmagineArticolo> immagineArticolos,
			Set<DettaglioOrdini> dettaglioOrdinis) {
		this.idarticolo = idarticolo;
		this.fornitori = fornitori;
		this.reparti = reparti;
		this.um = um;
		this.codfornitore = codfornitore;
		this.codbarre = codbarre;
		this.descrizione = descrizione;
		this.prezzoAcquisto = prezzoAcquisto;
		this.iva = iva;
		this.prezzoDettaglio = prezzoDettaglio;
		this.prezzoIngrosso = prezzoIngrosso;
		this.imballo = imballo;
		this.peso = peso;
		this.sconto = sconto;
		this.colore = colore;
		this.scortaMinima = scortaMinima;
		this.note = note;
		this.dataInserimento = dataInserimento;
		this.caricoIniziale = caricoIniziale;
		this.dettaglioCarichis = dettaglioCarichis;
		this.immagineArticolos = immagineArticolos;
		this.dettaglioOrdinis = dettaglioOrdinis;
	}

	public long getIdarticolo() {
		return this.idarticolo;
	}

	public void setIdarticolo(long idarticolo) {
		this.idarticolo = idarticolo;
	}

	public Fornitori getFornitori() {
		return this.fornitori;
	}

	public void setFornitori(Fornitori fornitori) {
		this.fornitori = fornitori;
	}

	public Reparti getReparti() {
		return this.reparti;
	}

	public void setReparti(Reparti reparti) {
		this.reparti = reparti;
	}

	public Um getUm() {
		return this.um;
	}

	public void setUm(Um um) {
		this.um = um;
	}

	public String getCodfornitore() {
		return this.codfornitore;
	}

	public void setCodfornitore(String codfornitore) {
		this.codfornitore = codfornitore;
	}

	public String getCodbarre() {
		return this.codbarre;
	}

	public void setCodbarre(String codbarre) {
		this.codbarre = codbarre;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Double getPrezzoAcquisto() {
		return this.prezzoAcquisto;
	}

	public void setPrezzoAcquisto(Double prezzoAcquisto) {
		this.prezzoAcquisto = prezzoAcquisto;
	}

	public Long getIva() {
		return this.iva;
	}

	public void setIva(Long iva) {
		this.iva = iva;
	}

	public Double getPrezzoDettaglio() {
		return this.prezzoDettaglio;
	}

	public void setPrezzoDettaglio(Double prezzoDettaglio) {
		this.prezzoDettaglio = prezzoDettaglio;
	}

	public Double getPrezzoIngrosso() {
		return this.prezzoIngrosso;
	}

	public void setPrezzoIngrosso(Double prezzoIngrosso) {
		this.prezzoIngrosso = prezzoIngrosso;
	}

	public String getImballo() {
		return this.imballo;
	}

	public void setImballo(String imballo) {
		this.imballo = imballo;
	}

	public Long getPeso() {
		return this.peso;
	}

	public void setPeso(Long peso) {
		this.peso = peso;
	}

	public Long getSconto() {
		return this.sconto;
	}

	public void setSconto(Long sconto) {
		this.sconto = sconto;
	}

	public String getColore() {
		return this.colore;
	}

	public void setColore(String colore) {
		this.colore = colore;
	}

	public Long getScortaMinima() {
		return this.scortaMinima;
	}

	public void setScortaMinima(Long scortaMinima) {
		this.scortaMinima = scortaMinima;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getDataInserimento() {
		return this.dataInserimento;
	}

	public void setDataInserimento(Date dataInserimento) {
		this.dataInserimento = dataInserimento;
	}

	public Long getCaricoIniziale() {
		return this.caricoIniziale;
	}

	public void setCaricoIniziale(Long caricoIniziale) {
		this.caricoIniziale = caricoIniziale;
	}

	public Set<DettaglioCarichi> getDettaglioCarichis() {
		return this.dettaglioCarichis;
	}

	public void setDettaglioCarichis(Set<DettaglioCarichi> dettaglioCarichis) {
		this.dettaglioCarichis = dettaglioCarichis;
	}

	public Set<ImmagineArticolo> getImmagineArticolos() {
		return this.immagineArticolos;
	}

	public void setImmagineArticolos(Set<ImmagineArticolo> immagineArticolos) {
		this.immagineArticolos = immagineArticolos;
	}

	public Set<DettaglioOrdini> getDettaglioOrdinis() {
		return this.dettaglioOrdinis;
	}

	public void setDettaglioOrdinis(Set<DettaglioOrdini> dettaglioOrdinis) {
		this.dettaglioOrdinis = dettaglioOrdinis;
	}

}
