package erreeffe.entity;

// Generated 28-giu-2009 12.52.19 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Aspetto generated by hbm2java
 */
public class Aspetto implements java.io.Serializable {

	private long idaspetto;
	private String nome;
	private Set<Ordini> ordinis = new HashSet<Ordini>(0);

	public Aspetto() {
	}

	public Aspetto(long idaspetto, String nome) {
		this.idaspetto = idaspetto;
		this.nome = nome;
	}

	public Aspetto(long idaspetto, String nome, Set<Ordini> ordinis) {
		this.idaspetto = idaspetto;
		this.nome = nome;
		this.ordinis = ordinis;
	}

	public long getIdaspetto() {
		return this.idaspetto;
	}

	public void setIdaspetto(long idaspetto) {
		this.idaspetto = idaspetto;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Ordini> getOrdinis() {
		return this.ordinis;
	}

	public void setOrdinis(Set<Ordini> ordinis) {
		this.ordinis = ordinis;
	}

}
