package erreeffe.entity;

// Generated 30-giu-2009 3.07.23 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Banca generated by hbm2java
 */
public class Banca implements java.io.Serializable {

	private long idbanca;
	private String ragioneSociale;
	private String note;
	private Set<ContoBancario> contoBancarios = new HashSet<ContoBancario>(0);

	public Banca() {
	}

	public Banca(long idbanca, String ragioneSociale) {
		this.idbanca = idbanca;
		this.ragioneSociale = ragioneSociale;
	}

	public Banca(long idbanca, String ragioneSociale, String note,
			Set<ContoBancario> contoBancarios) {
		this.idbanca = idbanca;
		this.ragioneSociale = ragioneSociale;
		this.note = note;
		this.contoBancarios = contoBancarios;
	}

	public long getIdbanca() {
		return this.idbanca;
	}

	public void setIdbanca(long idbanca) {
		this.idbanca = idbanca;
	}

	public String getRagioneSociale() {
		return this.ragioneSociale;
	}

	public void setRagioneSociale(String ragioneSociale) {
		this.ragioneSociale = ragioneSociale;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set<ContoBancario> getContoBancarios() {
		return this.contoBancarios;
	}

	public void setContoBancarios(Set<ContoBancario> contoBancarios) {
		this.contoBancarios = contoBancarios;
	}

}
