package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

/**
 * DettaglioConto generated by hbm2java
 */
public class DettaglioConto implements java.io.Serializable {

	private DettaglioContoId id;
	private Portata portata;
	private Conto conto;
	private Integer qta;
	private Double prezzoVendita;
	private Integer iva;

	public DettaglioConto() {
	}

	public DettaglioConto(DettaglioContoId id, Portata portata, Conto conto) {
		this.id = id;
		this.portata = portata;
		this.conto = conto;
	}

	public DettaglioConto(DettaglioContoId id, Portata portata, Conto conto,
			Integer qta, Double prezzoVendita, Integer iva) {
		this.id = id;
		this.portata = portata;
		this.conto = conto;
		this.qta = qta;
		this.prezzoVendita = prezzoVendita;
		this.iva = iva;
	}

	public DettaglioContoId getId() {
		return this.id;
	}

	public void setId(DettaglioContoId id) {
		this.id = id;
	}

	public Portata getPortata() {
		return this.portata;
	}

	public void setPortata(Portata portata) {
		this.portata = portata;
	}

	public Conto getConto() {
		return this.conto;
	}

	public void setConto(Conto conto) {
		this.conto = conto;
	}

	public Integer getQta() {
		return this.qta;
	}

	public void setQta(Integer qta) {
		this.qta = qta;
	}

	public Double getPrezzoVendita() {
		return this.prezzoVendita;
	}

	public void setPrezzoVendita(Double prezzoVendita) {
		this.prezzoVendita = prezzoVendita;
	}

	public Integer getIva() {
		return this.iva;
	}

	public void setIva(Integer iva) {
		this.iva = iva;
	}

}
