package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

/**
 * DettaglioContoId generated by hbm2java
 */
public class DettaglioContoId implements java.io.Serializable {

	private long portata;
	private long conto;

	public DettaglioContoId() {
	}

	public DettaglioContoId(long portata, long conto) {
		this.portata = portata;
		this.conto = conto;
	}

	public long getPortata() {
		return this.portata;
	}

	public void setPortata(long portata) {
		this.portata = portata;
	}

	public long getConto() {
		return this.conto;
	}

	public void setConto(long conto) {
		this.conto = conto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DettaglioContoId))
			return false;
		DettaglioContoId castOther = (DettaglioContoId) other;

		return (this.getPortata() == castOther.getPortata())
				&& (this.getConto() == castOther.getConto());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getPortata();
		result = 37 * result + (int) this.getConto();
		return result;
	}

}
