package erreeffe.entity;

// Generated 30-giu-2009 3.07.23 by Hibernate Tools 3.2.4.GA

/**
 * TmpScelti generated by hbm2java
 */
public class TmpScelti implements java.io.Serializable {

	private TmpSceltiId id;

	public TmpScelti() {
	}

	public TmpScelti(TmpSceltiId id) {
		this.id = id;
	}

	public TmpSceltiId getId() {
		return this.id;
	}

	public void setId(TmpSceltiId id) {
		this.id = id;
	}

}
