package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

/**
 * ArticoliCaricatiView generated by hbm2java
 */
public class ArticoliCaricatiView implements java.io.Serializable {

	private ArticoliCaricatiViewId id;

	public ArticoliCaricatiView() {
	}

	public ArticoliCaricatiView(ArticoliCaricatiViewId id) {
		this.id = id;
	}

	public ArticoliCaricatiViewId getId() {
		return this.id;
	}

	public void setId(ArticoliCaricatiViewId id) {
		this.id = id;
	}

}
