package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Carichi generated by hbm2java
 */
public class Carichi implements java.io.Serializable {

	private long idcarico;
	private Fornitori fornitori;
	private TipoDocumento tipoDocumento;
	private Date dataCarico;
	private Date oraCarico;
	private String note;
	private String numDocumento;
	private Date dataDocumento;
	private Set<DettaglioCarichi> dettaglioCarichis = new HashSet<DettaglioCarichi>(
			0);

	public Carichi() {
	}

	public Carichi(long idcarico) {
		this.idcarico = idcarico;
	}

	public Carichi(long idcarico, Fornitori fornitori,
			TipoDocumento tipoDocumento, Date dataCarico, Date oraCarico,
			String note, String numDocumento, Date dataDocumento,
			Set<DettaglioCarichi> dettaglioCarichis) {
		this.idcarico = idcarico;
		this.fornitori = fornitori;
		this.tipoDocumento = tipoDocumento;
		this.dataCarico = dataCarico;
		this.oraCarico = oraCarico;
		this.note = note;
		this.numDocumento = numDocumento;
		this.dataDocumento = dataDocumento;
		this.dettaglioCarichis = dettaglioCarichis;
	}

	public long getIdcarico() {
		return this.idcarico;
	}

	public void setIdcarico(long idcarico) {
		this.idcarico = idcarico;
	}

	public Fornitori getFornitori() {
		return this.fornitori;
	}

	public void setFornitori(Fornitori fornitori) {
		this.fornitori = fornitori;
	}

	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public Date getDataCarico() {
		return this.dataCarico;
	}

	public void setDataCarico(Date dataCarico) {
		this.dataCarico = dataCarico;
	}

	public Date getOraCarico() {
		return this.oraCarico;
	}

	public void setOraCarico(Date oraCarico) {
		this.oraCarico = oraCarico;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getNumDocumento() {
		return this.numDocumento;
	}

	public void setNumDocumento(String numDocumento) {
		this.numDocumento = numDocumento;
	}

	public Date getDataDocumento() {
		return this.dataDocumento;
	}

	public void setDataDocumento(Date dataDocumento) {
		this.dataDocumento = dataDocumento;
	}

	public Set<DettaglioCarichi> getDettaglioCarichis() {
		return this.dettaglioCarichis;
	}

	public void setDettaglioCarichis(Set<DettaglioCarichi> dettaglioCarichis) {
		this.dettaglioCarichis = dettaglioCarichis;
	}

}
