package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

import java.util.Date;

/**
 * Ddt generated by hbm2java
 */
public class Ddt implements java.io.Serializable {

	private long idddt;
	private Ordini ordini;
	private Aspetto aspetto;
	private Causale causale;
	private Long idcliente;
	private String diversaDest;
	private Double peso;
	private Date dataTr;
	private Date oraTr;
	private String consegna;
	private Long colli;
	private Long sconto;
	private String note;

	public Ddt() {
	}

	public Ddt(long idddt, Ordini ordini) {
		this.idddt = idddt;
		this.ordini = ordini;
	}

	public Ddt(long idddt, Ordini ordini, Aspetto aspetto, Causale causale,
			Long idcliente, String diversaDest, Double peso, Date dataTr,
			Date oraTr, String consegna, Long colli, Long sconto, String note) {
		this.idddt = idddt;
		this.ordini = ordini;
		this.aspetto = aspetto;
		this.causale = causale;
		this.idcliente = idcliente;
		this.diversaDest = diversaDest;
		this.peso = peso;
		this.dataTr = dataTr;
		this.oraTr = oraTr;
		this.consegna = consegna;
		this.colli = colli;
		this.sconto = sconto;
		this.note = note;
	}

	public long getIdddt() {
		return this.idddt;
	}

	public void setIdddt(long idddt) {
		this.idddt = idddt;
	}

	public Ordini getOrdini() {
		return this.ordini;
	}

	public void setOrdini(Ordini ordini) {
		this.ordini = ordini;
	}

	public Aspetto getAspetto() {
		return this.aspetto;
	}

	public void setAspetto(Aspetto aspetto) {
		this.aspetto = aspetto;
	}

	public Causale getCausale() {
		return this.causale;
	}

	public void setCausale(Causale causale) {
		this.causale = causale;
	}

	public Long getIdcliente() {
		return this.idcliente;
	}

	public void setIdcliente(Long idcliente) {
		this.idcliente = idcliente;
	}

	public String getDiversaDest() {
		return this.diversaDest;
	}

	public void setDiversaDest(String diversaDest) {
		this.diversaDest = diversaDest;
	}

	public Double getPeso() {
		return this.peso;
	}

	public void setPeso(Double peso) {
		this.peso = peso;
	}

	public Date getDataTr() {
		return this.dataTr;
	}

	public void setDataTr(Date dataTr) {
		this.dataTr = dataTr;
	}

	public Date getOraTr() {
		return this.oraTr;
	}

	public void setOraTr(Date oraTr) {
		this.oraTr = oraTr;
	}

	public String getConsegna() {
		return this.consegna;
	}

	public void setConsegna(String consegna) {
		this.consegna = consegna;
	}

	public Long getColli() {
		return this.colli;
	}

	public void setColli(Long colli) {
		this.colli = colli;
	}

	public Long getSconto() {
		return this.sconto;
	}

	public void setSconto(Long sconto) {
		this.sconto = sconto;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
