package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

import java.math.BigDecimal;

/**
 * GiacenzaArticoliAllViewId generated by hbm2java
 */
public class GiacenzaArticoliAllViewId implements java.io.Serializable {

	private Long idarticolo;
	private String codice;
	private String descrizione;
	private String um;
	private BigDecimal carico;
	private BigDecimal scarico;
	private BigDecimal deposito;
	private Double prezzoAcquisto;
	private Double prezzoTot;

	public GiacenzaArticoliAllViewId() {
	}

	public GiacenzaArticoliAllViewId(Long idarticolo, String codice,
			String descrizione, String um, BigDecimal carico,
			BigDecimal scarico, BigDecimal deposito, Double prezzoAcquisto,
			Double prezzoTot) {
		this.idarticolo = idarticolo;
		this.codice = codice;
		this.descrizione = descrizione;
		this.um = um;
		this.carico = carico;
		this.scarico = scarico;
		this.deposito = deposito;
		this.prezzoAcquisto = prezzoAcquisto;
		this.prezzoTot = prezzoTot;
	}

	public Long getIdarticolo() {
		return this.idarticolo;
	}

	public void setIdarticolo(Long idarticolo) {
		this.idarticolo = idarticolo;
	}

	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getUm() {
		return this.um;
	}

	public void setUm(String um) {
		this.um = um;
	}

	public BigDecimal getCarico() {
		return this.carico;
	}

	public void setCarico(BigDecimal carico) {
		this.carico = carico;
	}

	public BigDecimal getScarico() {
		return this.scarico;
	}

	public void setScarico(BigDecimal scarico) {
		this.scarico = scarico;
	}

	public BigDecimal getDeposito() {
		return this.deposito;
	}

	public void setDeposito(BigDecimal deposito) {
		this.deposito = deposito;
	}

	public Double getPrezzoAcquisto() {
		return this.prezzoAcquisto;
	}

	public void setPrezzoAcquisto(Double prezzoAcquisto) {
		this.prezzoAcquisto = prezzoAcquisto;
	}

	public Double getPrezzoTot() {
		return this.prezzoTot;
	}

	public void setPrezzoTot(Double prezzoTot) {
		this.prezzoTot = prezzoTot;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GiacenzaArticoliAllViewId))
			return false;
		GiacenzaArticoliAllViewId castOther = (GiacenzaArticoliAllViewId) other;

		return ((this.getIdarticolo() == castOther.getIdarticolo()) || (this
				.getIdarticolo() != null
				&& castOther.getIdarticolo() != null && this.getIdarticolo()
				.equals(castOther.getIdarticolo())))
				&& ((this.getCodice() == castOther.getCodice()) || (this
						.getCodice() != null
						&& castOther.getCodice() != null && this.getCodice()
						.equals(castOther.getCodice())))
				&& ((this.getDescrizione() == castOther.getDescrizione()) || (this
						.getDescrizione() != null
						&& castOther.getDescrizione() != null && this
						.getDescrizione().equals(castOther.getDescrizione())))
				&& ((this.getUm() == castOther.getUm()) || (this.getUm() != null
						&& castOther.getUm() != null && this.getUm().equals(
						castOther.getUm())))
				&& ((this.getCarico() == castOther.getCarico()) || (this
						.getCarico() != null
						&& castOther.getCarico() != null && this.getCarico()
						.equals(castOther.getCarico())))
				&& ((this.getScarico() == castOther.getScarico()) || (this
						.getScarico() != null
						&& castOther.getScarico() != null && this.getScarico()
						.equals(castOther.getScarico())))
				&& ((this.getDeposito() == castOther.getDeposito()) || (this
						.getDeposito() != null
						&& castOther.getDeposito() != null && this
						.getDeposito().equals(castOther.getDeposito())))
				&& ((this.getPrezzoAcquisto() == castOther.getPrezzoAcquisto()) || (this
						.getPrezzoAcquisto() != null
						&& castOther.getPrezzoAcquisto() != null && this
						.getPrezzoAcquisto().equals(
								castOther.getPrezzoAcquisto())))
				&& ((this.getPrezzoTot() == castOther.getPrezzoTot()) || (this
						.getPrezzoTot() != null
						&& castOther.getPrezzoTot() != null && this
						.getPrezzoTot().equals(castOther.getPrezzoTot())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdarticolo() == null ? 0 : this.getIdarticolo()
						.hashCode());
		result = 37 * result
				+ (getCodice() == null ? 0 : this.getCodice().hashCode());
		result = 37
				* result
				+ (getDescrizione() == null ? 0 : this.getDescrizione()
						.hashCode());
		result = 37 * result + (getUm() == null ? 0 : this.getUm().hashCode());
		result = 37 * result
				+ (getCarico() == null ? 0 : this.getCarico().hashCode());
		result = 37 * result
				+ (getScarico() == null ? 0 : this.getScarico().hashCode());
		result = 37 * result
				+ (getDeposito() == null ? 0 : this.getDeposito().hashCode());
		result = 37
				* result
				+ (getPrezzoAcquisto() == null ? 0 : this.getPrezzoAcquisto()
						.hashCode());
		result = 37 * result
				+ (getPrezzoTot() == null ? 0 : this.getPrezzoTot().hashCode());
		return result;
	}

}
