package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

/**
 * GiacenzaArticoliView generated by hbm2java
 */
public class GiacenzaArticoliView implements java.io.Serializable {

	private GiacenzaArticoliViewId id;

	public GiacenzaArticoliView() {
	}

	public GiacenzaArticoliView(GiacenzaArticoliViewId id) {
		this.id = id;
	}

	public GiacenzaArticoliViewId getId() {
		return this.id;
	}

	public void setId(GiacenzaArticoliViewId id) {
		this.id = id;
	}

}
