package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento implements java.io.Serializable {

	private long idpagamento;
	private String nome;
	private Set<Fattura> fatturas = new HashSet<Fattura>(0);

	public Pagamento() {
	}

	public Pagamento(long idpagamento, String nome) {
		this.idpagamento = idpagamento;
		this.nome = nome;
	}

	public Pagamento(long idpagamento, String nome, Set<Fattura> fatturas) {
		this.idpagamento = idpagamento;
		this.nome = nome;
		this.fatturas = fatturas;
	}

	public long getIdpagamento() {
		return this.idpagamento;
	}

	public void setIdpagamento(long idpagamento) {
		this.idpagamento = idpagamento;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Fattura> getFatturas() {
		return this.fatturas;
	}

	public void setFatturas(Set<Fattura> fatturas) {
		this.fatturas = fatturas;
	}

}
