package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

/**
 * QtaScaricateView generated by hbm2java
 */
public class QtaScaricateView implements java.io.Serializable {

	private QtaScaricateViewId id;

	public QtaScaricateView() {
	}

	public QtaScaricateView(QtaScaricateViewId id) {
		this.id = id;
	}

	public QtaScaricateViewId getId() {
		return this.id;
	}

	public void setId(QtaScaricateViewId id) {
		this.id = id;
	}

}
