package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reparti generated by hbm2java
 */
public class Reparti implements java.io.Serializable {

	private long idreparto;
	private Date dataCreazione;
	private String nome;
	private String descrizione;
	private Set<Articoli> articolis = new HashSet<Articoli>(0);

	public Reparti() {
	}

	public Reparti(long idreparto) {
		this.idreparto = idreparto;
	}

	public Reparti(long idreparto, Date dataCreazione, String nome,
			String descrizione, Set<Articoli> articolis) {
		this.idreparto = idreparto;
		this.dataCreazione = dataCreazione;
		this.nome = nome;
		this.descrizione = descrizione;
		this.articolis = articolis;
	}

	public long getIdreparto() {
		return this.idreparto;
	}

	public void setIdreparto(long idreparto) {
		this.idreparto = idreparto;
	}

	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Articoli> getArticolis() {
		return this.articolis;
	}

	public void setArticolis(Set<Articoli> articolis) {
		this.articolis = articolis;
	}

}
