package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

/**
 * ItalianiTot generated by hbm2java
 */
public class ItalianiTot implements java.io.Serializable {

	private ItalianiTotId id;

	public ItalianiTot() {
	}

	public ItalianiTot(ItalianiTotId id) {
		this.id = id;
	}

	public ItalianiTotId getId() {
		return this.id;
	}

	public void setId(ItalianiTotId id) {
		this.id = id;
	}

}
