package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Portata generated by hbm2java
 */
public class Portata implements java.io.Serializable {

	private long idportata;
	private CategoriaPortata categoriaPortata;
	private String descrizione;
	private Double prezzo;
	private Integer iva;
	private String note;
	private Integer ordine;
	private Set<DettaglioConto> dettaglioContos = new HashSet<DettaglioConto>(0);

	public Portata() {
	}

	public Portata(long idportata, String descrizione) {
		this.idportata = idportata;
		this.descrizione = descrizione;
	}

	public Portata(long idportata, CategoriaPortata categoriaPortata,
			String descrizione, Double prezzo, Integer iva, String note,
			Integer ordine, Set<DettaglioConto> dettaglioContos) {
		this.idportata = idportata;
		this.categoriaPortata = categoriaPortata;
		this.descrizione = descrizione;
		this.prezzo = prezzo;
		this.iva = iva;
		this.note = note;
		this.ordine = ordine;
		this.dettaglioContos = dettaglioContos;
	}

	public long getIdportata() {
		return this.idportata;
	}

	public void setIdportata(long idportata) {
		this.idportata = idportata;
	}

	public CategoriaPortata getCategoriaPortata() {
		return this.categoriaPortata;
	}

	public void setCategoriaPortata(CategoriaPortata categoriaPortata) {
		this.categoriaPortata = categoriaPortata;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Double getPrezzo() {
		return this.prezzo;
	}

	public void setPrezzo(Double prezzo) {
		this.prezzo = prezzo;
	}

	public Integer getIva() {
		return this.iva;
	}

	public void setIva(Integer iva) {
		this.iva = iva;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getOrdine() {
		return this.ordine;
	}

	public void setOrdine(Integer ordine) {
		this.ordine = ordine;
	}

	public Set<DettaglioConto> getDettaglioContos() {
		return this.dettaglioContos;
	}

	public void setDettaglioContos(Set<DettaglioConto> dettaglioContos) {
		this.dettaglioContos = dettaglioContos;
	}

}
