package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento implements java.io.Serializable {

	private long iddocumento;
	private String tipo;
	private String descrizione;
	private Set<Ordini> ordinis = new HashSet<Ordini>(0);
	private Set<Carichi> carichis = new HashSet<Carichi>(0);
	private Set<Carichi> carichis_1 = new HashSet<Carichi>(0);
	private Set<Ordini> ordinis_1 = new HashSet<Ordini>(0);

	public TipoDocumento() {
	}

	public TipoDocumento(long iddocumento, String tipo) {
		this.iddocumento = iddocumento;
		this.tipo = tipo;
	}

	public TipoDocumento(long iddocumento, String tipo, String descrizione,
			Set<Ordini> ordinis, Set<Carichi> carichis,
			Set<Carichi> carichis_1, Set<Ordini> ordinis_1) {
		this.iddocumento = iddocumento;
		this.tipo = tipo;
		this.descrizione = descrizione;
		this.ordinis = ordinis;
		this.carichis = carichis;
		this.carichis_1 = carichis_1;
		this.ordinis_1 = ordinis_1;
	}

	public long getIddocumento() {
		return this.iddocumento;
	}

	public void setIddocumento(long iddocumento) {
		this.iddocumento = iddocumento;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Ordini> getOrdinis() {
		return this.ordinis;
	}

	public void setOrdinis(Set<Ordini> ordinis) {
		this.ordinis = ordinis;
	}

	public Set<Carichi> getCarichis() {
		return this.carichis;
	}

	public void setCarichis(Set<Carichi> carichis) {
		this.carichis = carichis;
	}

	public Set<Carichi> getCarichis_1() {
		return this.carichis_1;
	}

	public void setCarichis_1(Set<Carichi> carichis_1) {
		this.carichis_1 = carichis_1;
	}

	public Set<Ordini> getOrdinis_1() {
		return this.ordinis_1;
	}

	public void setOrdinis_1(Set<Ordini> ordinis_1) {
		this.ordinis_1 = ordinis_1;
	}

}
