package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * DettaglioArticolo generated by hbm2java
 */
public class DettaglioArticolo implements java.io.Serializable {

	private long iddettaglio;
	private Articoli articoli;
	private String descrizione;
	private String descrizioneRidotta;
	private byte[] imgOriginale;
	private byte[] imgNonDisp;

	public DettaglioArticolo() {
	}

	public DettaglioArticolo(long iddettaglio, Articoli articoli) {
		this.iddettaglio = iddettaglio;
		this.articoli = articoli;
	}

	public DettaglioArticolo(long iddettaglio, Articoli articoli,
			String descrizione, String descrizioneRidotta, byte[] imgOriginale,
			byte[] imgNonDisp) {
		this.iddettaglio = iddettaglio;
		this.articoli = articoli;
		this.descrizione = descrizione;
		this.descrizioneRidotta = descrizioneRidotta;
		this.imgOriginale = imgOriginale;
		this.imgNonDisp = imgNonDisp;
	}

	public long getIddettaglio() {
		return this.iddettaglio;
	}

	public void setIddettaglio(long iddettaglio) {
		this.iddettaglio = iddettaglio;
	}

	public Articoli getArticoli() {
		return this.articoli;
	}

	public void setArticoli(Articoli articoli) {
		this.articoli = articoli;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getDescrizioneRidotta() {
		return this.descrizioneRidotta;
	}

	public void setDescrizioneRidotta(String descrizioneRidotta) {
		this.descrizioneRidotta = descrizioneRidotta;
	}

	public byte[] getImgOriginale() {
		return this.imgOriginale;
	}

	public void setImgOriginale(byte[] imgOriginale) {
		this.imgOriginale = imgOriginale;
	}

	public byte[] getImgNonDisp() {
		return this.imgNonDisp;
	}

	public void setImgNonDisp(byte[] imgNonDisp) {
		this.imgNonDisp = imgNonDisp;
	}

}
