package erreeffe.entity;

// Generated 28-giu-2009 12.52.19 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento implements java.io.Serializable {

	private long iddocumento;
	private String tipo;
	private String descrizione;
	private Set<Carichi> carichis = new HashSet<Carichi>(0);
	private Set<Ordini> ordinis = new HashSet<Ordini>(0);

	public TipoDocumento() {
	}

	public TipoDocumento(long iddocumento, String tipo) {
		this.iddocumento = iddocumento;
		this.tipo = tipo;
	}

	public TipoDocumento(long iddocumento, String tipo, String descrizione,
			Set<Carichi> carichis, Set<Ordini> ordinis) {
		this.iddocumento = iddocumento;
		this.tipo = tipo;
		this.descrizione = descrizione;
		this.carichis = carichis;
		this.ordinis = ordinis;
	}

	public long getIddocumento() {
		return this.iddocumento;
	}

	public void setIddocumento(long iddocumento) {
		this.iddocumento = iddocumento;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Carichi> getCarichis() {
		return this.carichis;
	}

	public void setCarichis(Set<Carichi> carichis) {
		this.carichis = carichis;
	}

	public Set<Ordini> getOrdinis() {
		return this.ordinis;
	}

	public void setOrdinis(Set<Ordini> ordinis) {
		this.ordinis = ordinis;
	}

}
