package erreeffe.entity;

// Generated 28-giu-2009 12.52.19 by Hibernate Tools 3.2.4.GA

/**
 * TmpEtichette generated by hbm2java
 */
public class TmpEtichette implements java.io.Serializable {

	private TmpEtichetteId id;

	public TmpEtichette() {
	}

	public TmpEtichette(TmpEtichetteId id) {
		this.id = id;
	}

	public TmpEtichetteId getId() {
		return this.id;
	}

	public void setId(TmpEtichetteId id) {
		this.id = id;
	}

}
