package erreeffe.entity;

// Generated 28-giu-2009 12.52.19 by Hibernate Tools 3.2.4.GA

/**
 * UtentiId generated by hbm2java
 */
public class UtentiId implements java.io.Serializable {

	private long idutente;
	private String nome;
	private String pwd;
	private Integer lettura;
	private Integer scrittura;
	private Integer esecuzione;
	private String note;

	public UtentiId() {
	}

	public UtentiId(long idutente, String nome) {
		this.idutente = idutente;
		this.nome = nome;
	}

	public UtentiId(long idutente, String nome, String pwd, Integer lettura,
			Integer scrittura, Integer esecuzione, String note) {
		this.idutente = idutente;
		this.nome = nome;
		this.pwd = pwd;
		this.lettura = lettura;
		this.scrittura = scrittura;
		this.esecuzione = esecuzione;
		this.note = note;
	}

	public long getIdutente() {
		return this.idutente;
	}

	public void setIdutente(long idutente) {
		this.idutente = idutente;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public Integer getLettura() {
		return this.lettura;
	}

	public void setLettura(Integer lettura) {
		this.lettura = lettura;
	}

	public Integer getScrittura() {
		return this.scrittura;
	}

	public void setScrittura(Integer scrittura) {
		this.scrittura = scrittura;
	}

	public Integer getEsecuzione() {
		return this.esecuzione;
	}

	public void setEsecuzione(Integer esecuzione) {
		this.esecuzione = esecuzione;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UtentiId))
			return false;
		UtentiId castOther = (UtentiId) other;

		return (this.getIdutente() == castOther.getIdutente())
				&& ((this.getNome() == castOther.getNome()) || (this.getNome() != null
						&& castOther.getNome() != null && this.getNome()
						.equals(castOther.getNome())))
				&& ((this.getPwd() == castOther.getPwd()) || (this.getPwd() != null
						&& castOther.getPwd() != null && this.getPwd().equals(
						castOther.getPwd())))
				&& ((this.getLettura() == castOther.getLettura()) || (this
						.getLettura() != null
						&& castOther.getLettura() != null && this.getLettura()
						.equals(castOther.getLettura())))
				&& ((this.getScrittura() == castOther.getScrittura()) || (this
						.getScrittura() != null
						&& castOther.getScrittura() != null && this
						.getScrittura().equals(castOther.getScrittura())))
				&& ((this.getEsecuzione() == castOther.getEsecuzione()) || (this
						.getEsecuzione() != null
						&& castOther.getEsecuzione() != null && this
						.getEsecuzione().equals(castOther.getEsecuzione())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null
						&& castOther.getNote() != null && this.getNote()
						.equals(castOther.getNote())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdutente();
		result = 37 * result
				+ (getNome() == null ? 0 : this.getNome().hashCode());
		result = 37 * result
				+ (getPwd() == null ? 0 : this.getPwd().hashCode());
		result = 37 * result
				+ (getLettura() == null ? 0 : this.getLettura().hashCode());
		result = 37 * result
				+ (getScrittura() == null ? 0 : this.getScrittura().hashCode());
		result = 37
				* result
				+ (getEsecuzione() == null ? 0 : this.getEsecuzione()
						.hashCode());
		result = 37 * result
				+ (getNote() == null ? 0 : this.getNote().hashCode());
		return result;
	}

}
