package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * Vettore generated by hbm2java
 */
public class Vettore implements java.io.Serializable {

	private VettoreId id;

	public Vettore() {
	}

	public Vettore(VettoreId id) {
		this.id = id;
	}

	public VettoreId getId() {
		return this.id;
	}

	public void setId(VettoreId id) {
		this.id = id;
	}

}
