package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * VettoreId generated by hbm2java
 */
public class VettoreId implements java.io.Serializable {

	private Long idvettore;
	private String denominazione;
	private String domicilio;
	private String recapito;

	public VettoreId() {
	}

	public VettoreId(Long idvettore, String denominazione, String domicilio,
			String recapito) {
		this.idvettore = idvettore;
		this.denominazione = denominazione;
		this.domicilio = domicilio;
		this.recapito = recapito;
	}

	public Long getIdvettore() {
		return this.idvettore;
	}

	public void setIdvettore(Long idvettore) {
		this.idvettore = idvettore;
	}

	public String getDenominazione() {
		return this.denominazione;
	}

	public void setDenominazione(String denominazione) {
		this.denominazione = denominazione;
	}

	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public String getRecapito() {
		return this.recapito;
	}

	public void setRecapito(String recapito) {
		this.recapito = recapito;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VettoreId))
			return false;
		VettoreId castOther = (VettoreId) other;

		return ((this.getIdvettore() == castOther.getIdvettore()) || (this
				.getIdvettore() != null
				&& castOther.getIdvettore() != null && this.getIdvettore()
				.equals(castOther.getIdvettore())))
				&& ((this.getDenominazione() == castOther.getDenominazione()) || (this
						.getDenominazione() != null
						&& castOther.getDenominazione() != null && this
						.getDenominazione()
						.equals(castOther.getDenominazione())))
				&& ((this.getDomicilio() == castOther.getDomicilio()) || (this
						.getDomicilio() != null
						&& castOther.getDomicilio() != null && this
						.getDomicilio().equals(castOther.getDomicilio())))
				&& ((this.getRecapito() == castOther.getRecapito()) || (this
						.getRecapito() != null
						&& castOther.getRecapito() != null && this
						.getRecapito().equals(castOther.getRecapito())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdvettore() == null ? 0 : this.getIdvettore().hashCode());
		result = 37
				* result
				+ (getDenominazione() == null ? 0 : this.getDenominazione()
						.hashCode());
		result = 37 * result
				+ (getDomicilio() == null ? 0 : this.getDomicilio().hashCode());
		result = 37 * result
				+ (getRecapito() == null ? 0 : this.getRecapito().hashCode());
		return result;
	}

}
