package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaPortata generated by hbm2java
 */
public class CategoriaPortata implements java.io.Serializable {

	private long id;
	private String descrizione;
	private String note;
	private Integer ordine;
	private Set<Portata> portatas = new HashSet<Portata>(0);

	public CategoriaPortata() {
	}

	public CategoriaPortata(long id, String descrizione) {
		this.id = id;
		this.descrizione = descrizione;
	}

	public CategoriaPortata(long id, String descrizione, String note,
			Integer ordine, Set<Portata> portatas) {
		this.id = id;
		this.descrizione = descrizione;
		this.note = note;
		this.ordine = ordine;
		this.portatas = portatas;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getOrdine() {
		return this.ordine;
	}

	public void setOrdine(Integer ordine) {
		this.ordine = ordine;
	}

	public Set<Portata> getPortatas() {
		return this.portatas;
	}

	public void setPortatas(Set<Portata> portatas) {
		this.portatas = portatas;
	}

}
