package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Modistatc59 generated by hbm2java
 */
public class Modistatc59 implements java.io.Serializable {

	private long idistat;
	private Date data;
	private long pnp;
	private Set<Italiani> italianis = new HashSet<Italiani>(0);
	private Set<Italiani> italianis_1 = new HashSet<Italiani>(0);
	private Set<Stranieri> stranieris = new HashSet<Stranieri>(0);
	private Set<Stranieri> stranieris_1 = new HashSet<Stranieri>(0);

	public Modistatc59() {
	}

	public Modistatc59(long idistat, Date data, long pnp) {
		this.idistat = idistat;
		this.data = data;
		this.pnp = pnp;
	}

	public Modistatc59(long idistat, Date data, long pnp,
			Set<Italiani> italianis, Set<Italiani> italianis_1,
			Set<Stranieri> stranieris, Set<Stranieri> stranieris_1) {
		this.idistat = idistat;
		this.data = data;
		this.pnp = pnp;
		this.italianis = italianis;
		this.italianis_1 = italianis_1;
		this.stranieris = stranieris;
		this.stranieris_1 = stranieris_1;
	}

	public long getIdistat() {
		return this.idistat;
	}

	public void setIdistat(long idistat) {
		this.idistat = idistat;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	public long getPnp() {
		return this.pnp;
	}

	public void setPnp(long pnp) {
		this.pnp = pnp;
	}

	public Set<Italiani> getItalianis() {
		return this.italianis;
	}

	public void setItalianis(Set<Italiani> italianis) {
		this.italianis = italianis;
	}

	public Set<Italiani> getItalianis_1() {
		return this.italianis_1;
	}

	public void setItalianis_1(Set<Italiani> italianis_1) {
		this.italianis_1 = italianis_1;
	}

	public Set<Stranieri> getStranieris() {
		return this.stranieris;
	}

	public void setStranieris(Set<Stranieri> stranieris) {
		this.stranieris = stranieris;
	}

	public Set<Stranieri> getStranieris_1() {
		return this.stranieris_1;
	}

	public void setStranieris_1(Set<Stranieri> stranieris_1) {
		this.stranieris_1 = stranieris_1;
	}

}
