package erreeffe.entity;

// Generated 30-giu-2009 3.07.23 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento implements java.io.Serializable {

	private long idpagamento;
	private String nome;
	private Set<Ordini> ordinisForPagamento = new HashSet<Ordini>(0);
	private Set<Ordini> ordinisForIdpagamento = new HashSet<Ordini>(0);

	public Pagamento() {
	}

	public Pagamento(long idpagamento, String nome) {
		this.idpagamento = idpagamento;
		this.nome = nome;
	}

	public Pagamento(long idpagamento, String nome,
			Set<Ordini> ordinisForPagamento, Set<Ordini> ordinisForIdpagamento) {
		this.idpagamento = idpagamento;
		this.nome = nome;
		this.ordinisForPagamento = ordinisForPagamento;
		this.ordinisForIdpagamento = ordinisForIdpagamento;
	}

	public long getIdpagamento() {
		return this.idpagamento;
	}

	public void setIdpagamento(long idpagamento) {
		this.idpagamento = idpagamento;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Ordini> getOrdinisForPagamento() {
		return this.ordinisForPagamento;
	}

	public void setOrdinisForPagamento(Set<Ordini> ordinisForPagamento) {
		this.ordinisForPagamento = ordinisForPagamento;
	}

	public Set<Ordini> getOrdinisForIdpagamento() {
		return this.ordinisForIdpagamento;
	}

	public void setOrdinisForIdpagamento(Set<Ordini> ordinisForIdpagamento) {
		this.ordinisForIdpagamento = ordinisForIdpagamento;
	}

}
