package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Tavolo generated by hbm2java
 */
public class Tavolo implements java.io.Serializable {

	private long idtavolo;
	private Sala sala;
	private int numeroTavolo;
	private int numeroPosti;
	private String descrizione;
	private Integer stato;
	private Set<Conto> contos = new HashSet<Conto>(0);

	public Tavolo() {
	}

	public Tavolo(long idtavolo, int numeroTavolo, int numeroPosti) {
		this.idtavolo = idtavolo;
		this.numeroTavolo = numeroTavolo;
		this.numeroPosti = numeroPosti;
	}

	public Tavolo(long idtavolo, Sala sala, int numeroTavolo, int numeroPosti,
			String descrizione, Integer stato, Set<Conto> contos) {
		this.idtavolo = idtavolo;
		this.sala = sala;
		this.numeroTavolo = numeroTavolo;
		this.numeroPosti = numeroPosti;
		this.descrizione = descrizione;
		this.stato = stato;
		this.contos = contos;
	}

	public long getIdtavolo() {
		return this.idtavolo;
	}

	public void setIdtavolo(long idtavolo) {
		this.idtavolo = idtavolo;
	}

	public Sala getSala() {
		return this.sala;
	}

	public void setSala(Sala sala) {
		this.sala = sala;
	}

	public int getNumeroTavolo() {
		return this.numeroTavolo;
	}

	public void setNumeroTavolo(int numeroTavolo) {
		this.numeroTavolo = numeroTavolo;
	}

	public int getNumeroPosti() {
		return this.numeroPosti;
	}

	public void setNumeroPosti(int numeroPosti) {
		this.numeroPosti = numeroPosti;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Integer getStato() {
		return this.stato;
	}

	public void setStato(Integer stato) {
		this.stato = stato;
	}

	public Set<Conto> getContos() {
		return this.contos;
	}

	public void setContos(Set<Conto> contos) {
		this.contos = contos;
	}

}
