package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

/**
 * TotaliModistatc59 generated by hbm2java
 */
public class TotaliModistatc59 implements java.io.Serializable {

	private TotaliModistatc59Id id;

	public TotaliModistatc59() {
	}

	public TotaliModistatc59(TotaliModistatc59Id id) {
		this.id = id;
	}

	public TotaliModistatc59Id getId() {
		return this.id;
	}

	public void setId(TotaliModistatc59Id id) {
		this.id = id;
	}

}
