package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Causale generated by hbm2java
 */
public class Causale implements java.io.Serializable {

	private long idcausale;
	private String nome;
	private Set<Ordini> ordinis = new HashSet<Ordini>(0);
	private Set<Ordini> ordinis_1 = new HashSet<Ordini>(0);

	public Causale() {
	}

	public Causale(long idcausale, String nome) {
		this.idcausale = idcausale;
		this.nome = nome;
	}

	public Causale(long idcausale, String nome, Set<Ordini> ordinis,
			Set<Ordini> ordinis_1) {
		this.idcausale = idcausale;
		this.nome = nome;
		this.ordinis = ordinis;
		this.ordinis_1 = ordinis_1;
	}

	public long getIdcausale() {
		return this.idcausale;
	}

	public void setIdcausale(long idcausale) {
		this.idcausale = idcausale;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Ordini> getOrdinis() {
		return this.ordinis;
	}

	public void setOrdinis(Set<Ordini> ordinis) {
		this.ordinis = ordinis;
	}

	public Set<Ordini> getOrdinis_1() {
		return this.ordinis_1;
	}

	public void setOrdinis_1(Set<Ordini> ordinis_1) {
		this.ordinis_1 = ordinis_1;
	}

}
