package erreeffe.entity;
// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Convenzione generated by hbm2java
 */
public class Convenzione  implements java.io.Serializable {


     private int idconvenzione;
     private Listino listino;
     private String descrizione;
     private String note;
     private Set<Periodo> periodos = new HashSet<Periodo>(0);

    public Convenzione() {
    }

	
    public Convenzione(int idconvenzione) {
        this.idconvenzione = idconvenzione;
    }
    public Convenzione(int idconvenzione, Listino listino, String descrizione, String note, Set<Periodo> periodos) {
       this.idconvenzione = idconvenzione;
       this.listino = listino;
       this.descrizione = descrizione;
       this.note = note;
       this.periodos = periodos;
    }
   
    public int getIdconvenzione() {
        return this.idconvenzione;
    }
    
    public void setIdconvenzione(int idconvenzione) {
        this.idconvenzione = idconvenzione;
    }
    public Listino getListino() {
        return this.listino;
    }
    
    public void setListino(Listino listino) {
        this.listino = listino;
    }
    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set<Periodo> getPeriodos() {
        return this.periodos;
    }
    
    public void setPeriodos(Set<Periodo> periodos) {
        this.periodos = periodos;
    }




}


