package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

/**
 * Italiani generated by hbm2java
 */
public class Italiani implements java.io.Serializable {

	private long iditaliani;
	private Modistatc59 modistatc59;
	private String provincia;
	private Long arrivati;
	private Long partiti;
	private Long presenti;

	public Italiani() {
	}

	public Italiani(long iditaliani, String provincia) {
		this.iditaliani = iditaliani;
		this.provincia = provincia;
	}

	public Italiani(long iditaliani, Modistatc59 modistatc59, String provincia,
			Long arrivati, Long partiti, Long presenti) {
		this.iditaliani = iditaliani;
		this.modistatc59 = modistatc59;
		this.provincia = provincia;
		this.arrivati = arrivati;
		this.partiti = partiti;
		this.presenti = presenti;
	}

	public long getIditaliani() {
		return this.iditaliani;
	}

	public void setIditaliani(long iditaliani) {
		this.iditaliani = iditaliani;
	}

	public Modistatc59 getModistatc59() {
		return this.modistatc59;
	}

	public void setModistatc59(Modistatc59 modistatc59) {
		this.modistatc59 = modistatc59;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public Long getArrivati() {
		return this.arrivati;
	}

	public void setArrivati(Long arrivati) {
		this.arrivati = arrivati;
	}

	public Long getPartiti() {
		return this.partiti;
	}

	public void setPartiti(Long partiti) {
		this.partiti = partiti;
	}

	public Long getPresenti() {
		return this.presenti;
	}

	public void setPresenti(Long presenti) {
		this.presenti = presenti;
	}

}
