package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Scelti generated by hbm2java
 */
public class Scelti implements java.io.Serializable {

	private SceltiId id;
	private Prenotazione prenotazione;
	private Aggiunta aggiunta;
	private Integer qta;
	private String tabella;
	private Date pos;
	private Double totale;

	public Scelti() {
	}

	public Scelti(SceltiId id, Prenotazione prenotazione, Aggiunta aggiunta) {
		this.id = id;
		this.prenotazione = prenotazione;
		this.aggiunta = aggiunta;
	}

	public Scelti(SceltiId id, Prenotazione prenotazione, Aggiunta aggiunta,
			Integer qta, String tabella, Date pos, Double totale) {
		this.id = id;
		this.prenotazione = prenotazione;
		this.aggiunta = aggiunta;
		this.qta = qta;
		this.tabella = tabella;
		this.pos = pos;
		this.totale = totale;
	}

	public SceltiId getId() {
		return this.id;
	}

	public void setId(SceltiId id) {
		this.id = id;
	}

	public Prenotazione getPrenotazione() {
		return this.prenotazione;
	}

	public void setPrenotazione(Prenotazione prenotazione) {
		this.prenotazione = prenotazione;
	}

	public Aggiunta getAggiunta() {
		return this.aggiunta;
	}

	public void setAggiunta(Aggiunta aggiunta) {
		this.aggiunta = aggiunta;
	}

	public Integer getQta() {
		return this.qta;
	}

	public void setQta(Integer qta) {
		this.qta = qta;
	}

	public String getTabella() {
		return this.tabella;
	}

	public void setTabella(String tabella) {
		this.tabella = tabella;
	}

	public Date getPos() {
		return this.pos;
	}

	public void setPos(Date pos) {
		this.pos = pos;
	}

	public Double getTotale() {
		return this.totale;
	}

	public void setTotale(Double totale) {
		this.totale = totale;
	}

}
