package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

/**
 * StranieriTot generated by hbm2java
 */
public class StranieriTot implements java.io.Serializable {

	private StranieriTotId id;

	public StranieriTot() {
	}

	public StranieriTot(StranieriTotId id) {
		this.id = id;
	}

	public StranieriTotId getId() {
		return this.id;
	}

	public void setId(StranieriTotId id) {
		this.id = id;
	}

}
