package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * TmpEtichette generated by hbm2java
 */
public class TmpEtichette implements java.io.Serializable {

	private TmpEtichetteId id;

	public TmpEtichette() {
	}

	public TmpEtichette(TmpEtichetteId id) {
		this.id = id;
	}

	public TmpEtichetteId getId() {
		return this.id;
	}

	public void setId(TmpEtichetteId id) {
		this.id = id;
	}

}
