package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * TmpSceltiId generated by hbm2java
 */
public class TmpSceltiId implements java.io.Serializable {

	private String descrizione;
	private Integer qta;
	private Double prezzo;
	private Double totale;

	public TmpSceltiId() {
	}

	public TmpSceltiId(String descrizione, Integer qta, Double prezzo,
			Double totale) {
		this.descrizione = descrizione;
		this.qta = qta;
		this.prezzo = prezzo;
		this.totale = totale;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Integer getQta() {
		return this.qta;
	}

	public void setQta(Integer qta) {
		this.qta = qta;
	}

	public Double getPrezzo() {
		return this.prezzo;
	}

	public void setPrezzo(Double prezzo) {
		this.prezzo = prezzo;
	}

	public Double getTotale() {
		return this.totale;
	}

	public void setTotale(Double totale) {
		this.totale = totale;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpSceltiId))
			return false;
		TmpSceltiId castOther = (TmpSceltiId) other;

		return ((this.getDescrizione() == castOther.getDescrizione()) || (this
				.getDescrizione() != null
				&& castOther.getDescrizione() != null && this.getDescrizione()
				.equals(castOther.getDescrizione())))
				&& ((this.getQta() == castOther.getQta()) || (this.getQta() != null
						&& castOther.getQta() != null && this.getQta().equals(
						castOther.getQta())))
				&& ((this.getPrezzo() == castOther.getPrezzo()) || (this
						.getPrezzo() != null
						&& castOther.getPrezzo() != null && this.getPrezzo()
						.equals(castOther.getPrezzo())))
				&& ((this.getTotale() == castOther.getTotale()) || (this
						.getTotale() != null
						&& castOther.getTotale() != null && this.getTotale()
						.equals(castOther.getTotale())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDescrizione() == null ? 0 : this.getDescrizione()
						.hashCode());
		result = 37 * result
				+ (getQta() == null ? 0 : this.getQta().hashCode());
		result = 37 * result
				+ (getPrezzo() == null ? 0 : this.getPrezzo().hashCode());
		result = 37 * result
				+ (getTotale() == null ? 0 : this.getTotale().hashCode());
		return result;
	}

}
