package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

/**
 * ArticoliScaricatiView generated by hbm2java
 */
public class ArticoliScaricatiView implements java.io.Serializable {

	private ArticoliScaricatiViewId id;

	public ArticoliScaricatiView() {
	}

	public ArticoliScaricatiView(ArticoliScaricatiViewId id) {
		this.id = id;
	}

	public ArticoliScaricatiViewId getId() {
		return this.id;
	}

	public void setId(ArticoliScaricatiViewId id) {
		this.id = id;
	}

}
