package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

/**
 * QtaScaricateView generated by hbm2java
 */
public class QtaScaricateView implements java.io.Serializable {

	private QtaScaricateViewId id;

	public QtaScaricateView() {
	}

	public QtaScaricateView(QtaScaricateViewId id) {
		this.id = id;
	}

	public QtaScaricateViewId getId() {
		return this.id;
	}

	public void setId(QtaScaricateViewId id) {
		this.id = id;
	}

}
