package it.infolabs.hibernate;

// Generated 21-lug-2009 1.39.59 by Hibernate Tools 3.2.4.GA

/**
 * TmpEtichette generated by hbm2java
 */
public class TmpEtichette implements java.io.Serializable {

	private TmpEtichetteId id;

	public TmpEtichette() {
	}

	public TmpEtichette(TmpEtichetteId id) {
		this.id = id;
	}

	public TmpEtichetteId getId() {
		return this.id;
	}

	public void setId(TmpEtichetteId id) {
		this.id = id;
	}

}
