package it.infolabs.hibernate;

// Generated 21-lug-2009 1.39.59 by Hibernate Tools 3.2.4.GA

/**
 * TmpScelti generated by hbm2java
 */
public class TmpScelti implements java.io.Serializable {

	private TmpSceltiId id;

	public TmpScelti() {
	}

	public TmpScelti(TmpSceltiId id) {
		this.id = id;
	}

	public TmpSceltiId getId() {
		return this.id;
	}

	public void setId(TmpSceltiId id) {
		this.id = id;
	}

}
