package erreeffe.entity;
// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento  implements java.io.Serializable {


     private long idpagamento;
     private String nome;
     private Set<Ordini> ordinis = new HashSet<Ordini>(0);

    public Pagamento() {
    }

	
    public Pagamento(long idpagamento, String nome) {
        this.idpagamento = idpagamento;
        this.nome = nome;
    }
    public Pagamento(long idpagamento, String nome, Set<Ordini> ordinis) {
       this.idpagamento = idpagamento;
       this.nome = nome;
       this.ordinis = ordinis;
    }
   
    public long getIdpagamento() {
        return this.idpagamento;
    }
    
    public void setIdpagamento(long idpagamento) {
        this.idpagamento = idpagamento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set<Ordini> getOrdinis() {
        return this.ordinis;
    }
    
    public void setOrdinis(Set<Ordini> ordinis) {
        this.ordinis = ordinis;
    }




}


