package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

/**
 * ArticoliScaricatiView generated by hbm2java
 */
public class ArticoliScaricatiView implements java.io.Serializable {

	private ArticoliScaricatiViewId id;

	public ArticoliScaricatiView() {
	}

	public ArticoliScaricatiView(ArticoliScaricatiViewId id) {
		this.id = id;
	}

	public ArticoliScaricatiViewId getId() {
		return this.id;
	}

	public void setId(ArticoliScaricatiViewId id) {
		this.id = id;
	}

}
