package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Causale generated by hbm2java
 */
public class Causale implements java.io.Serializable {

	private long idcausale;
	private String nome;
	private Set<Ddt> ddts = new HashSet<Ddt>(0);
	private Set<Fattura> fatturas = new HashSet<Fattura>(0);

	public Causale() {
	}

	public Causale(long idcausale, String nome) {
		this.idcausale = idcausale;
		this.nome = nome;
	}

	public Causale(long idcausale, String nome, Set<Ddt> ddts,
			Set<Fattura> fatturas) {
		this.idcausale = idcausale;
		this.nome = nome;
		this.ddts = ddts;
		this.fatturas = fatturas;
	}

	public long getIdcausale() {
		return this.idcausale;
	}

	public void setIdcausale(long idcausale) {
		this.idcausale = idcausale;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Ddt> getDdts() {
		return this.ddts;
	}

	public void setDdts(Set<Ddt> ddts) {
		this.ddts = ddts;
	}

	public Set<Fattura> getFatturas() {
		return this.fatturas;
	}

	public void setFatturas(Set<Fattura> fatturas) {
		this.fatturas = fatturas;
	}

}
