package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

/**
 * GiacenzaArticoliAllView generated by hbm2java
 */
public class GiacenzaArticoliAllView implements java.io.Serializable {

	private GiacenzaArticoliAllViewId id;

	public GiacenzaArticoliAllView() {
	}

	public GiacenzaArticoliAllView(GiacenzaArticoliAllViewId id) {
		this.id = id;
	}

	public GiacenzaArticoliAllViewId getId() {
		return this.id;
	}

	public void setId(GiacenzaArticoliAllViewId id) {
		this.id = id;
	}

}
