package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

/**
 * QtaCaricateView generated by hbm2java
 */
public class QtaCaricateView implements java.io.Serializable {

	private QtaCaricateViewId id;

	public QtaCaricateView() {
	}

	public QtaCaricateView(QtaCaricateViewId id) {
		this.id = id;
	}

	public QtaCaricateViewId getId() {
		return this.id;
	}

	public void setId(QtaCaricateViewId id) {
		this.id = id;
	}

}
