package rf.hibernate;

// Generated 18-dic-2007 17.22.08 by Hibernate Tools 3.2.0.CR1

/**
 * TmpEtichette generated by hbm2java
 */
public class TmpEtichette implements java.io.Serializable {

	private TmpEtichetteId id;

	public TmpEtichette() {
	}

	public TmpEtichette(TmpEtichetteId id) {
		this.id = id;
	}

	public TmpEtichetteId getId() {
		return this.id;
	}

	public void setId(TmpEtichetteId id) {
		this.id = id;
	}

}
