package it.infolabs.hibernate;

// Generated 21-lug-2009 1.39.59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Banca generated by hbm2java
 */
public class Banca implements java.io.Serializable {

	private long idbanca;
	private String ragioneSociale;
	private String note;
	private Set<ContoBancario> contoBancarios = new HashSet<ContoBancario>(0);
	private Set<ContoBancario> contoBancarios_1 = new HashSet<ContoBancario>(0);
	private Set<ContoBancario> contoBancarios_2 = new HashSet<ContoBancario>(0);

	public Banca() {
	}

	public Banca(long idbanca, String ragioneSociale) {
		this.idbanca = idbanca;
		this.ragioneSociale = ragioneSociale;
	}

	public Banca(long idbanca, String ragioneSociale, String note,
			Set<ContoBancario> contoBancarios,
			Set<ContoBancario> contoBancarios_1,
			Set<ContoBancario> contoBancarios_2) {
		this.idbanca = idbanca;
		this.ragioneSociale = ragioneSociale;
		this.note = note;
		this.contoBancarios = contoBancarios;
		this.contoBancarios_1 = contoBancarios_1;
		this.contoBancarios_2 = contoBancarios_2;
	}

	public long getIdbanca() {
		return this.idbanca;
	}

	public void setIdbanca(long idbanca) {
		this.idbanca = idbanca;
	}

	public String getRagioneSociale() {
		return this.ragioneSociale;
	}

	public void setRagioneSociale(String ragioneSociale) {
		this.ragioneSociale = ragioneSociale;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set<ContoBancario> getContoBancarios() {
		return this.contoBancarios;
	}

	public void setContoBancarios(Set<ContoBancario> contoBancarios) {
		this.contoBancarios = contoBancarios;
	}

	public Set<ContoBancario> getContoBancarios_1() {
		return this.contoBancarios_1;
	}

	public void setContoBancarios_1(Set<ContoBancario> contoBancarios_1) {
		this.contoBancarios_1 = contoBancarios_1;
	}

	public Set<ContoBancario> getContoBancarios_2() {
		return this.contoBancarios_2;
	}

	public void setContoBancarios_2(Set<ContoBancario> contoBancarios_2) {
		this.contoBancarios_2 = contoBancarios_2;
	}

}
