package it.infolabs.hibernate;

// Generated 21-lug-2009 1.39.59 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentoCliente generated by hbm2java
 */
public class DocumentoCliente implements java.io.Serializable {

	private long id;
	private String descrizione;
	private String abbreviazione;
	private Set<Clienti> clientis = new HashSet<Clienti>(0);
	private Set<Clienti> clientis_1 = new HashSet<Clienti>(0);
	private Set<Clienti> clientis_2 = new HashSet<Clienti>(0);

	public DocumentoCliente() {
	}

	public DocumentoCliente(long id, String descrizione) {
		this.id = id;
		this.descrizione = descrizione;
	}

	public DocumentoCliente(long id, String descrizione, String abbreviazione,
			Set<Clienti> clientis, Set<Clienti> clientis_1,
			Set<Clienti> clientis_2) {
		this.id = id;
		this.descrizione = descrizione;
		this.abbreviazione = abbreviazione;
		this.clientis = clientis;
		this.clientis_1 = clientis_1;
		this.clientis_2 = clientis_2;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getAbbreviazione() {
		return this.abbreviazione;
	}

	public void setAbbreviazione(String abbreviazione) {
		this.abbreviazione = abbreviazione;
	}

	public Set<Clienti> getClientis() {
		return this.clientis;
	}

	public void setClientis(Set<Clienti> clientis) {
		this.clientis = clientis;
	}

	public Set<Clienti> getClientis_1() {
		return this.clientis_1;
	}

	public void setClientis_1(Set<Clienti> clientis_1) {
		this.clientis_1 = clientis_1;
	}

	public Set<Clienti> getClientis_2() {
		return this.clientis_2;
	}

	public void setClientis_2(Set<Clienti> clientis_2) {
		this.clientis_2 = clientis_2;
	}

}
