package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private long id;
	private Date dataCreazione;
	private String descrizione;
	private String note;
	private Set<Reparti> repartis = new HashSet<Reparti>(0);
	private Set<Reparti> repartis_1 = new HashSet<Reparti>(0);

	public Categoria() {
	}

	public Categoria(long id, String descrizione) {
		this.id = id;
		this.descrizione = descrizione;
	}

	public Categoria(long id, Date dataCreazione, String descrizione,
			String note, Set<Reparti> repartis, Set<Reparti> repartis_1) {
		this.id = id;
		this.dataCreazione = dataCreazione;
		this.descrizione = descrizione;
		this.note = note;
		this.repartis = repartis;
		this.repartis_1 = repartis_1;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set<Reparti> getRepartis() {
		return this.repartis;
	}

	public void setRepartis(Set<Reparti> repartis) {
		this.repartis = repartis;
	}

	public Set<Reparti> getRepartis_1() {
		return this.repartis_1;
	}

	public void setRepartis_1(Set<Reparti> repartis_1) {
		this.repartis_1 = repartis_1;
	}

}
