package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

/**
 * ArticoliCaricatiViewId generated by hbm2java
 */
public class ArticoliCaricatiViewId implements java.io.Serializable {

	private Long idarticolo;
	private Long idcarico;
	private String codbarre;
	private String descrizione;
	private Long iva;
	private String um;
	private Double qta;
	private Double prezzoAcquisto;
	private Integer sconto;

	public ArticoliCaricatiViewId() {
	}

	public ArticoliCaricatiViewId(Long idarticolo, Long idcarico,
			String codbarre, String descrizione, Long iva, String um,
			Double qta, Double prezzoAcquisto, Integer sconto) {
		this.idarticolo = idarticolo;
		this.idcarico = idcarico;
		this.codbarre = codbarre;
		this.descrizione = descrizione;
		this.iva = iva;
		this.um = um;
		this.qta = qta;
		this.prezzoAcquisto = prezzoAcquisto;
		this.sconto = sconto;
	}

	public Long getIdarticolo() {
		return this.idarticolo;
	}

	public void setIdarticolo(Long idarticolo) {
		this.idarticolo = idarticolo;
	}

	public Long getIdcarico() {
		return this.idcarico;
	}

	public void setIdcarico(Long idcarico) {
		this.idcarico = idcarico;
	}

	public String getCodbarre() {
		return this.codbarre;
	}

	public void setCodbarre(String codbarre) {
		this.codbarre = codbarre;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Long getIva() {
		return this.iva;
	}

	public void setIva(Long iva) {
		this.iva = iva;
	}

	public String getUm() {
		return this.um;
	}

	public void setUm(String um) {
		this.um = um;
	}

	public Double getQta() {
		return this.qta;
	}

	public void setQta(Double qta) {
		this.qta = qta;
	}

	public Double getPrezzoAcquisto() {
		return this.prezzoAcquisto;
	}

	public void setPrezzoAcquisto(Double prezzoAcquisto) {
		this.prezzoAcquisto = prezzoAcquisto;
	}

	public Integer getSconto() {
		return this.sconto;
	}

	public void setSconto(Integer sconto) {
		this.sconto = sconto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ArticoliCaricatiViewId))
			return false;
		ArticoliCaricatiViewId castOther = (ArticoliCaricatiViewId) other;

		return ((this.getIdarticolo() == castOther.getIdarticolo()) || (this
				.getIdarticolo() != null
				&& castOther.getIdarticolo() != null && this.getIdarticolo()
				.equals(castOther.getIdarticolo())))
				&& ((this.getIdcarico() == castOther.getIdcarico()) || (this
						.getIdcarico() != null
						&& castOther.getIdcarico() != null && this
						.getIdcarico().equals(castOther.getIdcarico())))
				&& ((this.getCodbarre() == castOther.getCodbarre()) || (this
						.getCodbarre() != null
						&& castOther.getCodbarre() != null && this
						.getCodbarre().equals(castOther.getCodbarre())))
				&& ((this.getDescrizione() == castOther.getDescrizione()) || (this
						.getDescrizione() != null
						&& castOther.getDescrizione() != null && this
						.getDescrizione().equals(castOther.getDescrizione())))
				&& ((this.getIva() == castOther.getIva()) || (this.getIva() != null
						&& castOther.getIva() != null && this.getIva().equals(
						castOther.getIva())))
				&& ((this.getUm() == castOther.getUm()) || (this.getUm() != null
						&& castOther.getUm() != null && this.getUm().equals(
						castOther.getUm())))
				&& ((this.getQta() == castOther.getQta()) || (this.getQta() != null
						&& castOther.getQta() != null && this.getQta().equals(
						castOther.getQta())))
				&& ((this.getPrezzoAcquisto() == castOther.getPrezzoAcquisto()) || (this
						.getPrezzoAcquisto() != null
						&& castOther.getPrezzoAcquisto() != null && this
						.getPrezzoAcquisto().equals(
								castOther.getPrezzoAcquisto())))
				&& ((this.getSconto() == castOther.getSconto()) || (this
						.getSconto() != null
						&& castOther.getSconto() != null && this.getSconto()
						.equals(castOther.getSconto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdarticolo() == null ? 0 : this.getIdarticolo()
						.hashCode());
		result = 37 * result
				+ (getIdcarico() == null ? 0 : this.getIdcarico().hashCode());
		result = 37 * result
				+ (getCodbarre() == null ? 0 : this.getCodbarre().hashCode());
		result = 37
				* result
				+ (getDescrizione() == null ? 0 : this.getDescrizione()
						.hashCode());
		result = 37 * result
				+ (getIva() == null ? 0 : this.getIva().hashCode());
		result = 37 * result + (getUm() == null ? 0 : this.getUm().hashCode());
		result = 37 * result
				+ (getQta() == null ? 0 : this.getQta().hashCode());
		result = 37
				* result
				+ (getPrezzoAcquisto() == null ? 0 : this.getPrezzoAcquisto()
						.hashCode());
		result = 37 * result
				+ (getSconto() == null ? 0 : this.getSconto().hashCode());
		return result;
	}

}
