package it.infolabs.hibernate;

// Generated 1-feb-2010 0.56.14 by Hibernate Tools 3.2.4.GA

/**
 * ArticoliCaricatiView generated by hbm2java
 */
public class ArticoliCaricatiView implements java.io.Serializable {

	private ArticoliCaricatiViewId id;

	public ArticoliCaricatiView() {
	}

	public ArticoliCaricatiView(ArticoliCaricatiViewId id) {
		this.id = id;
	}

	public ArticoliCaricatiViewId getId() {
		return this.id;
	}

	public void setId(ArticoliCaricatiViewId id) {
		this.id = id;
	}

}
