package it.infolabs.hibernate;

// Generated 1-feb-2010 0.56.14 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Aspetto generated by hbm2java
 */
public class Aspetto implements java.io.Serializable {

	private long idaspetto;
	private String nome;
	private Set<Scarico> scaricos = new HashSet<Scarico>(0);
	private Set<Scarico> scaricos_1 = new HashSet<Scarico>(0);
	private Set<Scarico> scaricos_2 = new HashSet<Scarico>(0);

	public Aspetto() {
	}

	public Aspetto(long idaspetto, String nome) {
		this.idaspetto = idaspetto;
		this.nome = nome;
	}

	public Aspetto(long idaspetto, String nome, Set<Scarico> scaricos,
			Set<Scarico> scaricos_1, Set<Scarico> scaricos_2) {
		this.idaspetto = idaspetto;
		this.nome = nome;
		this.scaricos = scaricos;
		this.scaricos_1 = scaricos_1;
		this.scaricos_2 = scaricos_2;
	}

	public long getIdaspetto() {
		return this.idaspetto;
	}

	public void setIdaspetto(long idaspetto) {
		this.idaspetto = idaspetto;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Scarico> getScaricos() {
		return this.scaricos;
	}

	public void setScaricos(Set<Scarico> scaricos) {
		this.scaricos = scaricos;
	}

	public Set<Scarico> getScaricos_1() {
		return this.scaricos_1;
	}

	public void setScaricos_1(Set<Scarico> scaricos_1) {
		this.scaricos_1 = scaricos_1;
	}

	public Set<Scarico> getScaricos_2() {
		return this.scaricos_2;
	}

	public void setScaricos_2(Set<Scarico> scaricos_2) {
		this.scaricos_2 = scaricos_2;
	}

}
