package it.infolabs.hibernate;

// Generated 1-feb-2010 0.56.14 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Carico generated by hbm2java
 */
public class Carico implements java.io.Serializable {

	private long idcarico;
	private Fornitore fornitore;
	private TipoDocumento tipoDocumento;
	private Date dataCarico;
	private Date oraCarico;
	private String note;
	private String numDocumento;
	private Date dataDocumento;
	private Double totaleDocumento;
	private Integer sospeso;
	private Integer rifDoc;
	private Integer sconto;
	private Integer ivaDocumento;
	private Integer insPn;
	private Long riferimentoOrdine;
	private Set<DettaglioCarico> dettaglioCaricos = new HashSet<DettaglioCarico>(
			0);
	private Set<DettaglioCarico> dettaglioCaricos_1 = new HashSet<DettaglioCarico>(
			0);
	private Set<DettaglioCarico> dettaglioCaricos_2 = new HashSet<DettaglioCarico>(
			0);

	public Carico() {
	}

	public Carico(long idcarico) {
		this.idcarico = idcarico;
	}

	public Carico(long idcarico, Fornitore fornitore,
			TipoDocumento tipoDocumento, Date dataCarico, Date oraCarico,
			String note, String numDocumento, Date dataDocumento,
			Double totaleDocumento, Integer sospeso, Integer rifDoc,
			Integer sconto, Integer ivaDocumento, Integer insPn,
			Long riferimentoOrdine, Set<DettaglioCarico> dettaglioCaricos,
			Set<DettaglioCarico> dettaglioCaricos_1,
			Set<DettaglioCarico> dettaglioCaricos_2) {
		this.idcarico = idcarico;
		this.fornitore = fornitore;
		this.tipoDocumento = tipoDocumento;
		this.dataCarico = dataCarico;
		this.oraCarico = oraCarico;
		this.note = note;
		this.numDocumento = numDocumento;
		this.dataDocumento = dataDocumento;
		this.totaleDocumento = totaleDocumento;
		this.sospeso = sospeso;
		this.rifDoc = rifDoc;
		this.sconto = sconto;
		this.ivaDocumento = ivaDocumento;
		this.insPn = insPn;
		this.riferimentoOrdine = riferimentoOrdine;
		this.dettaglioCaricos = dettaglioCaricos;
		this.dettaglioCaricos_1 = dettaglioCaricos_1;
		this.dettaglioCaricos_2 = dettaglioCaricos_2;
	}

	public long getIdcarico() {
		return this.idcarico;
	}

	public void setIdcarico(long idcarico) {
		this.idcarico = idcarico;
	}

	public Fornitore getFornitore() {
		return this.fornitore;
	}

	public void setFornitore(Fornitore fornitore) {
		this.fornitore = fornitore;
	}

	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public Date getDataCarico() {
		return this.dataCarico;
	}

	public void setDataCarico(Date dataCarico) {
		this.dataCarico = dataCarico;
	}

	public Date getOraCarico() {
		return this.oraCarico;
	}

	public void setOraCarico(Date oraCarico) {
		this.oraCarico = oraCarico;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getNumDocumento() {
		return this.numDocumento;
	}

	public void setNumDocumento(String numDocumento) {
		this.numDocumento = numDocumento;
	}

	public Date getDataDocumento() {
		return this.dataDocumento;
	}

	public void setDataDocumento(Date dataDocumento) {
		this.dataDocumento = dataDocumento;
	}

	public Double getTotaleDocumento() {
		return this.totaleDocumento;
	}

	public void setTotaleDocumento(Double totaleDocumento) {
		this.totaleDocumento = totaleDocumento;
	}

	public Integer getSospeso() {
		return this.sospeso;
	}

	public void setSospeso(Integer sospeso) {
		this.sospeso = sospeso;
	}

	public Integer getRifDoc() {
		return this.rifDoc;
	}

	public void setRifDoc(Integer rifDoc) {
		this.rifDoc = rifDoc;
	}

	public Integer getSconto() {
		return this.sconto;
	}

	public void setSconto(Integer sconto) {
		this.sconto = sconto;
	}

	public Integer getIvaDocumento() {
		return this.ivaDocumento;
	}

	public void setIvaDocumento(Integer ivaDocumento) {
		this.ivaDocumento = ivaDocumento;
	}

	public Integer getInsPn() {
		return this.insPn;
	}

	public void setInsPn(Integer insPn) {
		this.insPn = insPn;
	}

	public Long getRiferimentoOrdine() {
		return this.riferimentoOrdine;
	}

	public void setRiferimentoOrdine(Long riferimentoOrdine) {
		this.riferimentoOrdine = riferimentoOrdine;
	}

	public Set<DettaglioCarico> getDettaglioCaricos() {
		return this.dettaglioCaricos;
	}

	public void setDettaglioCaricos(Set<DettaglioCarico> dettaglioCaricos) {
		this.dettaglioCaricos = dettaglioCaricos;
	}

	public Set<DettaglioCarico> getDettaglioCaricos_1() {
		return this.dettaglioCaricos_1;
	}

	public void setDettaglioCaricos_1(Set<DettaglioCarico> dettaglioCaricos_1) {
		this.dettaglioCaricos_1 = dettaglioCaricos_1;
	}

	public Set<DettaglioCarico> getDettaglioCaricos_2() {
		return this.dettaglioCaricos_2;
	}

	public void setDettaglioCaricos_2(Set<DettaglioCarico> dettaglioCaricos_2) {
		this.dettaglioCaricos_2 = dettaglioCaricos_2;
	}

}
