package it.infolabs.hibernate;

// Generated 1-feb-2010 0.56.14 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

	private long id;
	private Date dataCreazione;
	private String descrizione;
	private String note;
	private Set<Reparto> repartos = new HashSet<Reparto>(0);
	private Set<Reparto> repartos_1 = new HashSet<Reparto>(0);

	public Categoria() {
	}

	public Categoria(long id, String descrizione) {
		this.id = id;
		this.descrizione = descrizione;
	}

	public Categoria(long id, Date dataCreazione, String descrizione,
			String note, Set<Reparto> repartos, Set<Reparto> repartos_1) {
		this.id = id;
		this.dataCreazione = dataCreazione;
		this.descrizione = descrizione;
		this.note = note;
		this.repartos = repartos;
		this.repartos_1 = repartos_1;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Date getDataCreazione() {
		return this.dataCreazione;
	}

	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set<Reparto> getRepartos() {
		return this.repartos;
	}

	public void setRepartos(Set<Reparto> repartos) {
		this.repartos = repartos;
	}

	public Set<Reparto> getRepartos_1() {
		return this.repartos_1;
	}

	public void setRepartos_1(Set<Reparto> repartos_1) {
		this.repartos_1 = repartos_1;
	}

}
