package it.infolabs.hibernate;

// Generated 1-feb-2010 0.56.14 by Hibernate Tools 3.2.4.GA

/**
 * DettaglioCarico generated by hbm2java
 */
public class DettaglioCarico implements java.io.Serializable {

	private DettaglioCaricoId id;
	private Carico carico;
	private Articolo articolo;
	private double qta;
	private Double prezzoAcquisto;
	private Integer sconto;

	public DettaglioCarico() {
	}

	public DettaglioCarico(DettaglioCaricoId id, Carico carico,
			Articolo articolo, double qta) {
		this.id = id;
		this.carico = carico;
		this.articolo = articolo;
		this.qta = qta;
	}

	public DettaglioCarico(DettaglioCaricoId id, Carico carico,
			Articolo articolo, double qta, Double prezzoAcquisto, Integer sconto) {
		this.id = id;
		this.carico = carico;
		this.articolo = articolo;
		this.qta = qta;
		this.prezzoAcquisto = prezzoAcquisto;
		this.sconto = sconto;
	}

	public DettaglioCaricoId getId() {
		return this.id;
	}

	public void setId(DettaglioCaricoId id) {
		this.id = id;
	}

	public Carico getCarico() {
		return this.carico;
	}

	public void setCarico(Carico carico) {
		this.carico = carico;
	}

	public Articolo getArticolo() {
		return this.articolo;
	}

	public void setArticolo(Articolo articolo) {
		this.articolo = articolo;
	}

	public double getQta() {
		return this.qta;
	}

	public void setQta(double qta) {
		this.qta = qta;
	}

	public Double getPrezzoAcquisto() {
		return this.prezzoAcquisto;
	}

	public void setPrezzoAcquisto(Double prezzoAcquisto) {
		this.prezzoAcquisto = prezzoAcquisto;
	}

	public Integer getSconto() {
		return this.sconto;
	}

	public void setSconto(Integer sconto) {
		this.sconto = sconto;
	}

}
