package it.infolabs.hibernate;

// Generated 1-feb-2010 0.56.14 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DocumentoCliente generated by hbm2java
 */
public class DocumentoCliente implements java.io.Serializable {

	private long id;
	private String descrizione;
	private String abbreviazione;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);
	private Set<Cliente> clientes_1 = new HashSet<Cliente>(0);
	private Set<Cliente> clientes_2 = new HashSet<Cliente>(0);

	public DocumentoCliente() {
	}

	public DocumentoCliente(long id, String descrizione) {
		this.id = id;
		this.descrizione = descrizione;
	}

	public DocumentoCliente(long id, String descrizione, String abbreviazione,
			Set<Cliente> clientes, Set<Cliente> clientes_1,
			Set<Cliente> clientes_2) {
		this.id = id;
		this.descrizione = descrizione;
		this.abbreviazione = abbreviazione;
		this.clientes = clientes;
		this.clientes_1 = clientes_1;
		this.clientes_2 = clientes_2;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getAbbreviazione() {
		return this.abbreviazione;
	}

	public void setAbbreviazione(String abbreviazione) {
		this.abbreviazione = abbreviazione;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	public Set<Cliente> getClientes_1() {
		return this.clientes_1;
	}

	public void setClientes_1(Set<Cliente> clientes_1) {
		this.clientes_1 = clientes_1;
	}

	public Set<Cliente> getClientes_2() {
		return this.clientes_2;
	}

	public void setClientes_2(Set<Cliente> clientes_2) {
		this.clientes_2 = clientes_2;
	}

}
