package it.infolabs.hibernate;

// Generated 1-feb-2010 0.56.14 by Hibernate Tools 3.2.4.GA

/**
 * Documento generated by hbm2java
 */
public class Documento implements java.io.Serializable {

	private DocumentoId id;

	public Documento() {
	}

	public Documento(DocumentoId id) {
		this.id = id;
	}

	public DocumentoId getId() {
		return this.id;
	}

	public void setId(DocumentoId id) {
		this.id = id;
	}

}
