package it.infolabs.hibernate;

// Generated 23-lug-2009 0.07.34 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Nazionalita generated by hbm2java
 */
public class Nazionalita implements java.io.Serializable {

	private long idnazionalita;
	private String descrizione;
	private Set<Clienti> clientis = new HashSet<Clienti>(0);
	private Set<Clienti> clientis_1 = new HashSet<Clienti>(0);
	private Set<Clienti> clientis_2 = new HashSet<Clienti>(0);

	public Nazionalita() {
	}

	public Nazionalita(long idnazionalita, String descrizione) {
		this.idnazionalita = idnazionalita;
		this.descrizione = descrizione;
	}

	public Nazionalita(long idnazionalita, String descrizione,
			Set<Clienti> clientis, Set<Clienti> clientis_1,
			Set<Clienti> clientis_2) {
		this.idnazionalita = idnazionalita;
		this.descrizione = descrizione;
		this.clientis = clientis;
		this.clientis_1 = clientis_1;
		this.clientis_2 = clientis_2;
	}

	public long getIdnazionalita() {
		return this.idnazionalita;
	}

	public void setIdnazionalita(long idnazionalita) {
		this.idnazionalita = idnazionalita;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Clienti> getClientis() {
		return this.clientis;
	}

	public void setClientis(Set<Clienti> clientis) {
		this.clientis = clientis;
	}

	public Set<Clienti> getClientis_1() {
		return this.clientis_1;
	}

	public void setClientis_1(Set<Clienti> clientis_1) {
		this.clientis_1 = clientis_1;
	}

	public Set<Clienti> getClientis_2() {
		return this.clientis_2;
	}

	public void setClientis_2(Set<Clienti> clientis_2) {
		this.clientis_2 = clientis_2;
	}

}
