package it.infolabs.hibernate;

// Generated 3-lug-2010 0.47.58 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Nazionalita generated by hbm2java
 */
public class Nazionalita implements java.io.Serializable {

	private long idnazionalita;
	private String descrizione;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Nazionalita() {
	}

	public Nazionalita(long idnazionalita, String descrizione) {
		this.idnazionalita = idnazionalita;
		this.descrizione = descrizione;
	}

	public Nazionalita(long idnazionalita, String descrizione,
			Set<Cliente> clientes) {
		this.idnazionalita = idnazionalita;
		this.descrizione = descrizione;
		this.clientes = clientes;
	}

	public long getIdnazionalita() {
		return this.idnazionalita;
	}

	public void setIdnazionalita(long idnazionalita) {
		this.idnazionalita = idnazionalita;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
