package it.infolabs.hibernate;

// Generated 27-giu-2010 12.59.16 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Paese generated by hbm2java
 */
public class Paese implements java.io.Serializable {

	private long id;
	private Character descrizione;
	private Set<Destinazione> destinaziones = new HashSet<Destinazione>(0);

	public Paese() {
	}

	public Paese(long id) {
		this.id = id;
	}

	public Paese(long id, Character descrizione, Set<Destinazione> destinaziones) {
		this.id = id;
		this.descrizione = descrizione;
		this.destinaziones = destinaziones;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Character getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(Character descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Destinazione> getDestinaziones() {
		return this.destinaziones;
	}

	public void setDestinaziones(Set<Destinazione> destinaziones) {
		this.destinaziones = destinaziones;
	}

}
