package it.infolabs.hibernate;

// Generated 3-lug-2010 0.47.58 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Pannelli generated by hbm2java
 */
public class Pannelli implements java.io.Serializable {

	private long idpannelli;
	private String nome;
	private Set<Articolo> articolos = new HashSet<Articolo>(0);

	public Pannelli() {
	}

	public Pannelli(long idpannelli) {
		this.idpannelli = idpannelli;
	}

	public Pannelli(long idpannelli, String nome, Set<Articolo> articolos) {
		this.idpannelli = idpannelli;
		this.nome = nome;
		this.articolos = articolos;
	}

	public long getIdpannelli() {
		return this.idpannelli;
	}

	public void setIdpannelli(long idpannelli) {
		this.idpannelli = idpannelli;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Articolo> getArticolos() {
		return this.articolos;
	}

	public void setArticolos(Set<Articolo> articolos) {
		this.articolos = articolos;
	}

}
