package it.infolabs.hibernate;

// Generated 6-mag-2010 0.12.00 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Stato generated by hbm2java
 */
public class Stato implements java.io.Serializable {

	private long id;
	private String descrizione;
	private Set<Ordine> ordines = new HashSet<Ordine>(0);
	private Set<Ordine> ordines_1 = new HashSet<Ordine>(0);

	public Stato() {
	}

	public Stato(long id) {
		this.id = id;
	}

	public Stato(long id, String descrizione, Set<Ordine> ordines,
			Set<Ordine> ordines_1) {
		this.id = id;
		this.descrizione = descrizione;
		this.ordines = ordines;
		this.ordines_1 = ordines_1;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Ordine> getOrdines() {
		return this.ordines;
	}

	public void setOrdines(Set<Ordine> ordines) {
		this.ordines = ordines;
	}

	public Set<Ordine> getOrdines_1() {
		return this.ordines_1;
	}

	public void setOrdines_1(Set<Ordine> ordines_1) {
		this.ordines_1 = ordines_1;
	}

}
