package it.infolabs.hibernate;

// Generated 21-lug-2009 1.39.59 by Hibernate Tools 3.2.4.GA

/**
 * TmpEtichetteId generated by hbm2java
 */
public class TmpEtichetteId implements java.io.Serializable {

	private long id;
	private String codice;
	private String descrizione;
	private Double prezzo;
	private String note;
	private String codbarre;

	public TmpEtichetteId() {
	}

	public TmpEtichetteId(long id) {
		this.id = id;
	}

	public TmpEtichetteId(long id, String codice, String descrizione,
			Double prezzo, String note, String codbarre) {
		this.id = id;
		this.codice = codice;
		this.descrizione = descrizione;
		this.prezzo = prezzo;
		this.note = note;
		this.codbarre = codbarre;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCodice() {
		return this.codice;
	}

	public void setCodice(String codice) {
		this.codice = codice;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Double getPrezzo() {
		return this.prezzo;
	}

	public void setPrezzo(Double prezzo) {
		this.prezzo = prezzo;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}
	
	public String getCodbarre() {
		return this.codbarre;
	}

	public void setCodbarre(String codbarre) {
		this.codbarre = codbarre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmpEtichetteId))
			return false;
		TmpEtichetteId castOther = (TmpEtichetteId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getCodice() == castOther.getCodice()) || (this
						.getCodice() != null
						&& castOther.getCodice() != null && this.getCodice()
						.equals(castOther.getCodice())))
				&& ((this.getDescrizione() == castOther.getDescrizione()) || (this
						.getDescrizione() != null
						&& castOther.getDescrizione() != null && this
						.getDescrizione().equals(castOther.getDescrizione())))
				&& ((this.getPrezzo() == castOther.getPrezzo()) || (this
						.getPrezzo() != null
						&& castOther.getPrezzo() != null && this.getPrezzo()
						.equals(castOther.getPrezzo())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null
						&& castOther.getNote() != null && this.getNote()
						.equals(castOther.getNote())))
				&& ((this.getCodbarre() == castOther.getCodbarre()) || (this.getCodbarre() != null
						&& castOther.getCodbarre() != null && this.getCodbarre()
						.equals(castOther.getCodbarre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getId();
		result = 37 * result
				+ (getCodice() == null ? 0 : this.getCodice().hashCode());
		result = 37
				* result
				+ (getDescrizione() == null ? 0 : this.getDescrizione()
						.hashCode());
		result = 37 * result
				+ (getPrezzo() == null ? 0 : this.getPrezzo().hashCode());
		result = 37 * result
				+ (getNote() == null ? 0 : this.getNote().hashCode());
		result = 37 * result
				+ (getCodbarre() == null ? 0 : this.getCodbarre().hashCode());
		return result;
	}

}
