package it.infolabs.hibernate;

// Generated 1-feb-2010 0.56.14 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Ente generated by hbm2java
 */
public class Ente implements java.io.Serializable {

	private long idente;
	private String descrizione;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);
	private Set<Cliente> clientes_1 = new HashSet<Cliente>(0);
	private Set<Cliente> clientes_2 = new HashSet<Cliente>(0);

	public Ente() {
	}

	public Ente(long idente, String descrizione) {
		this.idente = idente;
		this.descrizione = descrizione;
	}

	public Ente(long idente, String descrizione, Set<Cliente> clientes,
			Set<Cliente> clientes_1, Set<Cliente> clientes_2) {
		this.idente = idente;
		this.descrizione = descrizione;
		this.clientes = clientes;
		this.clientes_1 = clientes_1;
		this.clientes_2 = clientes_2;
	}

	public long getIdente() {
		return this.idente;
	}

	public void setIdente(long idente) {
		this.idente = idente;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

	public Set<Cliente> getClientes_1() {
		return this.clientes_1;
	}

	public void setClientes_1(Set<Cliente> clientes_1) {
		this.clientes_1 = clientes_1;
	}

	public Set<Cliente> getClientes_2() {
		return this.clientes_2;
	}

	public void setClientes_2(Set<Cliente> clientes_2) {
		this.clientes_2 = clientes_2;
	}

}
