package it.infolabs.hibernate;

// Generated 23-lug-2009 17.43.49 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Um generated by hbm2java
 */
public class Um implements java.io.Serializable {

	private long idum;
	private String nome;
	private String descrizione;
	private Set<Articolo> articolis = new HashSet<Articolo>(0);
	private Set<Articolo> articolis_1 = new HashSet<Articolo>(0);
	private Set<Articolo> articolis_2 = new HashSet<Articolo>(0);

	public Um() {
	}

	public Um(long idum, String nome) {
		this.idum = idum;
		this.nome = nome;
	}

	public Um(long idum, String nome, String descrizione,
			Set<Articolo> articolis, Set<Articolo> articolis_1,
			Set<Articolo> articolis_2) {
		this.idum = idum;
		this.nome = nome;
		this.descrizione = descrizione;
		this.articolis = articolis;
		this.articolis_1 = articolis_1;
		this.articolis_2 = articolis_2;
	}

	public long getIdum() {
		return this.idum;
	}

	public void setIdum(long idum) {
		this.idum = idum;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Set<Articolo> getArticolis() {
		return this.articolis;
	}

	public void setArticolis(Set<Articolo> articolis) {
		this.articolis = articolis;
	}

	public Set<Articolo> getArticolis_1() {
		return this.articolis_1;
	}

	public void setArticolis_1(Set<Articolo> articolis_1) {
		this.articolis_1 = articolis_1;
	}

	public Set<Articolo> getArticolis_2() {
		return this.articolis_2;
	}

	public void setArticolis_2(Set<Articolo> articolis_2) {
		this.articolis_2 = articolis_2;
	}

}
