package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * DettagliDocumenti generated by hbm2java
 */
public class DettagliDocumenti implements java.io.Serializable {

	private int id;
	private Documenti documenti;
	private String descrizione;
	private Integer aliquota;
	private Integer qta;
	private Double prezzo;
	private Double prezzoTotale;
	private Double imponibile;
	private Double imposta;

	public DettagliDocumenti() {
	}

	public DettagliDocumenti(int id, Documenti documenti, String descrizione) {
		this.id = id;
		this.documenti = documenti;
		this.descrizione = descrizione;
	}

	public DettagliDocumenti(int id, Documenti documenti, String descrizione,
			Integer aliquota, Integer qta, Double prezzo, Double prezzoTotale,
			Double imponibile, Double imposta) {
		this.id = id;
		this.documenti = documenti;
		this.descrizione = descrizione;
		this.aliquota = aliquota;
		this.qta = qta;
		this.prezzo = prezzo;
		this.prezzoTotale = prezzoTotale;
		this.imponibile = imponibile;
		this.imposta = imposta;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Documenti getDocumenti() {
		return this.documenti;
	}

	public void setDocumenti(Documenti documenti) {
		this.documenti = documenti;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public Integer getAliquota() {
		return this.aliquota;
	}

	public void setAliquota(Integer aliquota) {
		this.aliquota = aliquota;
	}

	public Integer getQta() {
		return this.qta;
	}

	public void setQta(Integer qta) {
		this.qta = qta;
	}

	public Double getPrezzo() {
		return this.prezzo;
	}

	public void setPrezzo(Double prezzo) {
		this.prezzo = prezzo;
	}

	public Double getPrezzoTotale() {
		return this.prezzoTotale;
	}

	public void setPrezzoTotale(Double prezzoTotale) {
		this.prezzoTotale = prezzoTotale;
	}

	public Double getImponibile() {
		return this.imponibile;
	}

	public void setImponibile(Double imponibile) {
		this.imponibile = imponibile;
	}

	public Double getImposta() {
		return this.imposta;
	}

	public void setImposta(Double imposta) {
		this.imposta = imposta;
	}

}
