package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Listino generated by hbm2java
 */
public class Listino implements java.io.Serializable {

	private long idlistino;
	private String descrizione;
	private String note;
	private Set<Convenzione> convenziones = new HashSet<Convenzione>(0);
	private Set<Convenzione> convenziones_1 = new HashSet<Convenzione>(0);

	public Listino() {
	}

	public Listino(long idlistino, String descrizione) {
		this.idlistino = idlistino;
		this.descrizione = descrizione;
	}

	public Listino(long idlistino, String descrizione, String note,
			Set<Convenzione> convenziones, Set<Convenzione> convenziones_1) {
		this.idlistino = idlistino;
		this.descrizione = descrizione;
		this.note = note;
		this.convenziones = convenziones;
		this.convenziones_1 = convenziones_1;
	}

	public long getIdlistino() {
		return this.idlistino;
	}

	public void setIdlistino(long idlistino) {
		this.idlistino = idlistino;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Set<Convenzione> getConvenziones() {
		return this.convenziones;
	}

	public void setConvenziones(Set<Convenzione> convenziones) {
		this.convenziones = convenziones;
	}

	public Set<Convenzione> getConvenziones_1() {
		return this.convenziones_1;
	}

	public void setConvenziones_1(Set<Convenzione> convenziones_1) {
		this.convenziones_1 = convenziones_1;
	}

}
