package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Pagamento generated by hbm2java
 */
public class Pagamento implements java.io.Serializable {

	private long idpagamento;
	private String nome;
	private Set<Ordini> ordinisForIdpagamento = new HashSet<Ordini>(0);
	private Set<Ordini> ordinisForPagamento = new HashSet<Ordini>(0);
	private Set<Conto> contos = new HashSet<Conto>(0);
	private Set<Ordini> ordinisForPagamento_1 = new HashSet<Ordini>(0);
	private Set<Ordini> ordinisForIdpagamento_1 = new HashSet<Ordini>(0);

	public Pagamento() {
	}

	public Pagamento(long idpagamento, String nome) {
		this.idpagamento = idpagamento;
		this.nome = nome;
	}

	public Pagamento(long idpagamento, String nome,
			Set<Ordini> ordinisForIdpagamento, Set<Ordini> ordinisForPagamento,
			Set<Conto> contos, Set<Ordini> ordinisForPagamento_1,
			Set<Ordini> ordinisForIdpagamento_1) {
		this.idpagamento = idpagamento;
		this.nome = nome;
		this.ordinisForIdpagamento = ordinisForIdpagamento;
		this.ordinisForPagamento = ordinisForPagamento;
		this.contos = contos;
		this.ordinisForPagamento_1 = ordinisForPagamento_1;
		this.ordinisForIdpagamento_1 = ordinisForIdpagamento_1;
	}

	public long getIdpagamento() {
		return this.idpagamento;
	}

	public void setIdpagamento(long idpagamento) {
		this.idpagamento = idpagamento;
	}

	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Set<Ordini> getOrdinisForIdpagamento() {
		return this.ordinisForIdpagamento;
	}

	public void setOrdinisForIdpagamento(Set<Ordini> ordinisForIdpagamento) {
		this.ordinisForIdpagamento = ordinisForIdpagamento;
	}

	public Set<Ordini> getOrdinisForPagamento() {
		return this.ordinisForPagamento;
	}

	public void setOrdinisForPagamento(Set<Ordini> ordinisForPagamento) {
		this.ordinisForPagamento = ordinisForPagamento;
	}

	public Set<Conto> getContos() {
		return this.contos;
	}

	public void setContos(Set<Conto> contos) {
		this.contos = contos;
	}

	public Set<Ordini> getOrdinisForPagamento_1() {
		return this.ordinisForPagamento_1;
	}

	public void setOrdinisForPagamento_1(Set<Ordini> ordinisForPagamento_1) {
		this.ordinisForPagamento_1 = ordinisForPagamento_1;
	}

	public Set<Ordini> getOrdinisForIdpagamento_1() {
		return this.ordinisForIdpagamento_1;
	}

	public void setOrdinisForIdpagamento_1(Set<Ordini> ordinisForIdpagamento_1) {
		this.ordinisForIdpagamento_1 = ordinisForIdpagamento_1;
	}

}
