package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Periodo generated by hbm2java
 */
public class Periodo implements java.io.Serializable {

	private long idperiodo;
	private Convenzione convenzione;
	private Double prezzo;
	private Date dal;
	private Date al;
	private String descrizione;

	public Periodo() {
	}

	public Periodo(long idperiodo) {
		this.idperiodo = idperiodo;
	}

	public Periodo(long idperiodo, Convenzione convenzione, Double prezzo,
			Date dal, Date al, String descrizione) {
		this.idperiodo = idperiodo;
		this.convenzione = convenzione;
		this.prezzo = prezzo;
		this.dal = dal;
		this.al = al;
		this.descrizione = descrizione;
	}

	public long getIdperiodo() {
		return this.idperiodo;
	}

	public void setIdperiodo(long idperiodo) {
		this.idperiodo = idperiodo;
	}

	public Convenzione getConvenzione() {
		return this.convenzione;
	}

	public void setConvenzione(Convenzione convenzione) {
		this.convenzione = convenzione;
	}

	public Double getPrezzo() {
		return this.prezzo;
	}

	public void setPrezzo(Double prezzo) {
		this.prezzo = prezzo;
	}

	public Date getDal() {
		return this.dal;
	}

	public void setDal(Date dal) {
		this.dal = dal;
	}

	public Date getAl() {
		return this.al;
	}

	public void setAl(Date al) {
		this.al = al;
	}

	public String getDescrizione() {
		return this.descrizione;
	}

	public void setDescrizione(String descrizione) {
		this.descrizione = descrizione;
	}

}
