package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * Progressivi generated by hbm2java
 */
public class Progressivi implements java.io.Serializable {

	private ProgressiviId id;

	public Progressivi() {
	}

	public Progressivi(ProgressiviId id) {
		this.id = id;
	}

	public ProgressiviId getId() {
		return this.id;
	}

	public void setId(ProgressiviId id) {
		this.id = id;
	}

}
