package erreeffe.entity;

// Generated 19-nov-2008 20.32.14 by Hibernate Tools 3.2.2.GA

/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	private long idprovincia;
	private String provincia;
	private String targa;

	public Provincia() {
	}

	public Provincia(long idprovincia, String provincia) {
		this.idprovincia = idprovincia;
		this.provincia = provincia;
	}

	public Provincia(long idprovincia, String provincia, String targa) {
		this.idprovincia = idprovincia;
		this.provincia = provincia;
		this.targa = targa;
	}

	public long getIdprovincia() {
		return this.idprovincia;
	}

	public void setIdprovincia(long idprovincia) {
		this.idprovincia = idprovincia;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getTarga() {
		return this.targa;
	}

	public void setTarga(String targa) {
		this.targa = targa;
	}

}
