package erreeffe.entity;

// Generated 20-nov-2008 2.05.44 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia implements java.io.Serializable {

	private long idprovincia;
	private String provincia;
	private String targa;
	private Set<Fornitori> fornitoris = new HashSet<Fornitori>(0);
	private Set<Fornitori> fornitoris_1 = new HashSet<Fornitori>(0);
	private Set<Clienti> clientis = new HashSet<Clienti>(0);
	private Set<Clienti> clientis_1 = new HashSet<Clienti>(0);

	public Provincia() {
	}

	public Provincia(long idprovincia, String provincia) {
		this.idprovincia = idprovincia;
		this.provincia = provincia;
	}

	public Provincia(long idprovincia, String provincia, String targa,
			Set<Fornitori> fornitoris, Set<Fornitori> fornitoris_1,
			Set<Clienti> clientis, Set<Clienti> clientis_1) {
		this.idprovincia = idprovincia;
		this.provincia = provincia;
		this.targa = targa;
		this.fornitoris = fornitoris;
		this.fornitoris_1 = fornitoris_1;
		this.clientis = clientis;
		this.clientis_1 = clientis_1;
	}

	public long getIdprovincia() {
		return this.idprovincia;
	}

	public void setIdprovincia(long idprovincia) {
		this.idprovincia = idprovincia;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getTarga() {
		return this.targa;
	}

	public void setTarga(String targa) {
		this.targa = targa;
	}

	public Set<Fornitori> getFornitoris() {
		return this.fornitoris;
	}

	public void setFornitoris(Set<Fornitori> fornitoris) {
		this.fornitoris = fornitoris;
	}

	public Set<Fornitori> getFornitoris_1() {
		return this.fornitoris_1;
	}

	public void setFornitoris_1(Set<Fornitori> fornitoris_1) {
		this.fornitoris_1 = fornitoris_1;
	}

	public Set<Clienti> getClientis() {
		return this.clientis;
	}

	public void setClientis(Set<Clienti> clientis) {
		this.clientis = clientis;
	}

	public Set<Clienti> getClientis_1() {
		return this.clientis_1;
	}

	public void setClientis_1(Set<Clienti> clientis_1) {
		this.clientis_1 = clientis_1;
	}

}
